label change_group_talk :
    if month == 3 :
        if week == 1 :
            if day == 0 :
                $ grouptalk.add("날짜|2월 27일 금요일")
                $ grouptalk.add("주인공|문화정보학과 OO학번 단톡방입니다!!")
                $ grouptalk.add("해장중|오올 뻔대! 술 그렇게 마시고도 일 잘하는데?")
                $ grouptalk.add("유현재|캬 단톡방 빠르게 파는 클라스~~")
                $ grouptalk.add("김진일|역시 내가 사람 보는 눈은 있지ㅋㅋㅋㅋ")
                $ grouptalk.add("안금지|뻔대 뽑힌 거 축하해…!")
                $ grouptalk.add("오덕현|후훗...역시 이 내가 인정한 [[리더]]...축하한다구 친구")
                $ grouptalk.add("노미래|ㅊㅋㅊㅋ~")
                $ grouptalk.add("동삼용|와 내가 다른 과 친구들한테 물어봤는데 신입생끼리만 있는 톡방은 우리과가 제일 빨리 파진것 같은데? 일 처리 속도 실화냐~")
                $ grouptalk.add("박대현|뻔대 멋있다~ 열일하자! 뻔대님~~")
                $ grouptalk.add("주인공|와우 얘들아 고마워!!ㅠㅜ 너희가 뻔대로 뽑아준만큼 그 믿음에 최대한 보답할게!! 우리 앞으로 뻔모도 자주하고 동기들끼리도 많이 만나자아!!!!!")

            #if day == 1 :
                # $ grouptalk.add("날짜|3월 2일 월요일")
                # $ grouptalk.add("주인공|와 다들 첫 등교 어땠어? 난 뭔가 쉬는시간이 안 정해져있는 것 자체가 되게 묘하더라")
                # $ grouptalk.add("동삼용|꿀잼꿀잼")
                # $ grouptalk.add("박대현|넌 외특인데 그런 말은 어디서 그렇게 배워오는거냐..")
                # $ grouptalk.add("동삼용|다른과 인싸 친구가 알려줬음! 꿀잼꿀잼~")
                # $ grouptalk.add("유현재|오 나 15학점 듣는데, 미래랑 15학점 겹강임 신기신기")
                # $ grouptalk.add("노미래|와 그래도 밥먹을 때 외롭진 않겠다! 수업마치고 밥 같이 먹자 ㅎㅎㅎ")
                # $ grouptalk.add("주인공|오옹 뭐냐 둘이 그 정도면 운명인데?")
                # $ grouptalk.add("김진일|뭐 대학도 별 거 없던데?? ㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("오덕현|5252~ 수업 정도야 이 오레사마에게는 간단한 일이라굿 (퍽)")
                # $ grouptalk.add("해장중|개강 기념 술팟 구함 (1/34)")
                # $ grouptalk.add("동삼용|개강 기념 술팟2222")
                # $ grouptalk.add("주인공|3333")
                # $ grouptalk.add("안금지|미안 나는 오늘 다른 일이 있어서 안 될 것 같아..")
                # $ grouptalk.add("주인공|ㄱㅊㄱㅊ")

            elif day == 2 :
                $ grouptalk.add("날짜|3월 3일 화요일")
                $ grouptalk.add("해장중|와 오늘 9시 수업인데 눈 떠보니 지금 시간임")
                $ grouptalk.add("연속|이게 말로만 듣던 자체 휴강이냐")
                $ grouptalk.add("연속|....으 머리야")
                $ grouptalk.add("김진일|오늘 어차피 OT라 출첵 안했음 ㄱㅊㄱㅊ")
                $ grouptalk.add("해장중|진일아 너 분명히 나랑 같이 첫 차까지 마셨는데 왜 이렇게 멀쩡하냐...")
                $ grouptalk.add("연속|으으 해장이나 하러가야지..")
                # $ grouptalk.add("동삼용|나는 오늘 공강이었지롱~ ㄱㅇㄷ~")
                # $ grouptalk.add("주인공|와 공강 너무 부럽다. 난 왜 공강이 없냐...")
                # $ grouptalk.add("유현재|수강신청 망했대요~")
                # $ grouptalk.add("노미래|그렇대요~")
                # $ grouptalk.add("박대현|저 두 사람 겹강 많다고 죽 잘맞는거 봐라...")
                # $ grouptalk.add("오덕현|솔로는..서럽..달..까..?")

            #elif day == 3 :
                # $ grouptalk.add("날짜|3월 4일 수요일")
                # $ grouptalk.add("동삼용|내가 아는 다른 과 친구가 다음주 월요일에 동소제라는 걸 한대!")
                # $ grouptalk.add("해장중|오옹 동소제~ 동아리 소개제~")
                # $ grouptalk.add("오덕현|후훗, 풍문을 듣자하니 이 학교에는 <감상 클럽>이라는 게 있다고 하던데..")
                # $ grouptalk.add("연속|얼마나 잘 운영되고 있는지 보고 싶다..랄까...(먼산)")
                # $ grouptalk.add("박대현|와 근데 삼용아 넌 진짜 그런 소식들 잘 알아온다. 멋진데?")
                # $ grouptalk.add("동삼용|하하 내가 이런 소식은 알아서 잘 들고오는 편이지")
                # $ grouptalk.add("주인공|오오 동아리 재밌겠다. 너네는 하고 싶은거 없어?")
                # $ grouptalk.add("김진일|나는 운동 동아리...! 복싱 동아리 같은거 재밌을 것 같은데?")
                # $ grouptalk.add("유현재|그러는 뻔대야 너는 뭐할건데??")
                # $ grouptalk.add("주인공|음...아직 정하진 않았는데")
                # $ grouptalk.add("주인공|아마 나랑 같이 입학한 고향 친구랑 같은 동아리 들어갈 것 같은데?")
                # $ grouptalk.add("노미래|ㅇㅎ 많이 친한가봐")
                # $ grouptalk.add("주인공|응 그래도 유치원부터 고등학교까지 같이 다니면서")
                # $ grouptalk.add("주인공|중학교 때 부터는 밴드부도 같이 했으니까 많이 친하짘ㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|걔랑 이 학교 같이 붙었을 때 진짜 좋았어")
                # $ grouptalk.add("해장중|와 그 정도면 ㄹㅇ로 소울메이트네 인정한다")

            #elif day == 4 :
                # $ grouptalk.add("날짜|3월 5일 목요일")
                # $ grouptalk.add("해장중|엌ㅋㅋㅋㅋㅋㅋㅋ나 어제 술 마시고 페북에 뭔 짓 한거짘ㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("박대현|너 500 마시다가 맥주는 음료수지!")
                # $ grouptalk.add("연속|이러면서 소주 시킬 때부터 뭔가 쎄하더라")
                # $ grouptalk.add("김진일|장중아 너는 아직 나랑 술 마시기엔 너무 약해. 더 강해져서 와라")
                # $ grouptalk.add("해장중|받들어 모시겠습니다. 스승님")
                # $ grouptalk.add("오덕현|지나친 음주는 간을 파.괘.한다네...쿡쿡쿡")
                # $ grouptalk.add("연속|너희의 <해독 기관>이 과연 언제까지 버틸 수 있을까..? 후하하하")
                # $ grouptalk.add("주인공|맞아 얘들아 조금은 적당히 마셔..그러다 몸 상할라 ㅠㅜ")
                # $ grouptalk.add("유현재|술자리 있을 때마다 병샷하는 네가 할 말은 아니지 않아?")
                # $ grouptalk.add("노미래|동의")
                # $ grouptalk.add("동삼용|동의222222")
                # $ grouptalk.add("박대현|동의3333333333")
                # $ grouptalk.add("주인공|엌ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")

            #elif day == 5 :
                # $ grouptalk.add("날짜|3월 6일 금요일")
                # $ grouptalk.add("주인공|맞다 너희들 다음 주 총엠인 건 알지?")
                # $ grouptalk.add("동삼용|와 총엠~ 재밌겠다~!~!")
                # $ grouptalk.add("해장중|총엠이면 고~학번 선배님들이 맛있는 양주 사오겠지??")
                # $ grouptalk.add("연속|무조건 그 때까지 버틴다...")
                # $ grouptalk.add("김진일|양주하면 또 나지, 너희 발렌타인 30년산이라고 들어봤냐?")
                # $ grouptalk.add("안금지|아..엠티는 별로..재미 없을 것 같은데..")
                # $ grouptalk.add("오덕현|엠티! 그 사건이 바로 다음주란 말인가..")
                # $ grouptalk.add("연속|큭..어쩔 수 없지 이 날을 위해 단련한 궁극의 술 게임을..!")
                # $ grouptalk.add("연속|바로..지금!!")
                # $ grouptalk.add("유현재|으음 많이 마실 것 같은데 숙취해소제라도 챙겨놔야겠다..")
                # $ grouptalk.add("노미래|오옹 좋은 생각이야!")
                # $ grouptalk.add("박대현|와 첫 엠티..재밌겠지? ㅎㅎㅎ")

            elif day == 6 :
                $ grouptalk.add("날짜|3월 7일 토요일")
                $ grouptalk.add("주인공|입학 후 첫 주말인데 다들 뭐하고 지냈어?")
                $ grouptalk.add("해장중|어제 달리고 이제 일어남 ㅎㅎㅎ...")
                $ grouptalk.add("연속|으 속 안좋아 해장하러 가야겠다.")
                $ grouptalk.add("동삼용|간단하게 서울 이곳저곳 돌아 다녔어")
                $ grouptalk.add("연속|다른 학교 주변 돌아다녔는데, 그 학교에 있는 아는 애들이 선배들한테 들은 맛집 같은 거 추천해주더라")
                $ grouptalk.add("연속|혹시 다른 학교 갈 일 있으면 물어보면 대답해줄게!")
                $ grouptalk.add("유현재|오옹..나 내일 낙성대학교 쪽 놀러갈 것 같은데 주변 맛집 알려주실?")
                $ grouptalk.add("동삼용|갠톡 ㄱㄱ")
                $ grouptalk.add("유현재|오키~")
                $ grouptalk.add("김진일|난 그냥 아는 형님들 만나고 왔지 ㅎㅎ")
                $ grouptalk.add("연속|나중에 힘 쓸일 있으면 말해 다 도와준다 ㅎㅎ")
                # $ grouptalk.add("안금지|그래;;")
                # $ grouptalk.add("오덕현|와타시는...밀린 <명작>들을 봤달..까..?")
                # $ grouptalk.add("주인공|ㅋㅋㅋㅋ다들 그래도 좋은 주말 보낸 것 같아서 다행이네!")

        elif week == 2 :
            if day == 0 :
                $ grouptalk.add("날짜|3월 8일 일요일")
                $ grouptalk.add("동삼용|야~ 현재야 너 어제 낙성대주변 맛집 물어본 게 이것 때문이었냐~ 와~")
                $ grouptalk.add("유현재|??? 뭐가?????")
                $ grouptalk.add("동삼용|에이 다 알면서~")
                $ grouptalk.add("연속|너 미래랑 내가 알려준 맛집에서 둘이서 오붓하게 밥 먹는거 봤는데?")
                $ grouptalk.add("박대현|@노미래")
                $ grouptalk.add("해장중|@노미래22")
                $ grouptalk.add("노미래|아 너희들이 생각하는 그런거 아니야 ㅠㅜㅜ")
                $ grouptalk.add("유현재|ㅇㅇ 그런 거 아니고, 그냥 저번 주에 나 수업 못 갔을 때")
                $ grouptalk.add("연속|수업 내용 알려주고 그래서 그 보답으로 밥 산 것 뿐이야")
                $ grouptalk.add("김진일|과연 그럴까? ㅎㅎㅎㅎ")
                $ grouptalk.add("주인공|너희 설마...Hoxy..?")
                $ grouptalk.add("해장중|해 명 해 해 명 해")
                $ grouptalk.add("노미래|아니야;;")
                $ grouptalk.add("유현재|아니야;;")
                $ grouptalk.add("해장중|와;; 땀 개수까지 똑같은 것 보소...저 정도면 천생연분이다..")
                $ grouptalk.add("오덕현|큽...이래서 인싸들이란..")

            #elif day == 1 :
                # $ grouptalk.add("날짜|3월 9일 월요일")
                # $ grouptalk.add("해장중|와 나 동소제 놀러갔다가 우리 뻔대 노래하는 거 들었는데 장난아니던데;;")
                # $ grouptalk.add("유현재|오~ 그렇게 잘해?")
                # $ grouptalk.add("해장중|ㄹㅇ 음원 튼 줄, 블루투스 스피커 없나 찾아봤다니까?")
                # $ grouptalk.add("주인공|에이 과찬이야...ㅎㅎㅎㅎ")
                # $ grouptalk.add("동삼용|과찬은 무슨 나도 같이 들었는데 진짜 잘 부르더라~")
                # $ grouptalk.add("박대현|ㅇㅈㅇㅈ, 옆에서 기타 치던 친구가 전에 말한 고등학교 동창이지?")
                # $ grouptalk.add("연속|걔도 엄청 잘 치더라, 둘이 케미  진짜 잘 맞던데? ㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|그 친구가 실력 하나는 끝내주지!")
                # $ grouptalk.add("오덕현|그래서 그 밴-드-부에는 가입하기로 결정한 걸까나..?")
                # $ grouptalk.add("주인공|응, 동아도 맘에 들어하고, 선배들도 다들 괜찮아보여서 바로 가입 신청했어.")
                # $ grouptalk.add("노미래|오옹 밴드라니 다음에 공연 같은 거 하면 꼭 보러갈게!!")
                # $ grouptalk.add("연속|애들 반응 보니까 기대되는데~")
                # $ grouptalk.add("주인공|ㅋㅋㅋㅋㅋ 홍보 오지게 할 거니까 많이 오렴 ^^")

            #elif day == 2 :
                # $ grouptalk.add("날짜|3월 10일 화요일")
                # $ grouptalk.add("김진일|장중아 오늘 대출 고마웠다.")
                # $ grouptalk.add("해장중|허허 숙취에 찌든 몸을 이끌고 오전 수업 들으러 왔더니..")
                # $ grouptalk.add("연속|같이 듣는 친구 녀석은 대출해달라 하고...자연스레 나 혼자 독강..")
                # $ grouptalk.add("연속|이 빚은 컨디션으로 받겠다..쏴라..!")
                # $ grouptalk.add("김진일|뭐 그 정도야 충분히 사줄 수 있짘ㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|지난 주에는 자체휴강, 이번 주에는 대출...저 수업 담당하는 교수님이 불쌍하다")
                # $ grouptalk.add("오덕현|흠...이의 없다는....")
                # $ grouptalk.add("대현 |뭐 저게 나름 대학생활 로망아니겠냨ㅋㅋㅋ")
                # $ grouptalk.add("안금지|그렇다고 저렇게 살고 싶진 않아...")
                # $ grouptalk.add("동삼용|그런 의미로 로망 더 즐기실 분~")
                # $ grouptalk.add("연속|오늘 저녁에 술 마셔요~!")
                # $ grouptalk.add("해장중|나나나나나나나나나ㅏ나ㅏ나나나ㅏ나")
                # $ grouptalk.add("주인공|어휴...")
                # $ grouptalk.add("유현재|그러면서 술자리 가면 항상 있더라 뻔대야..?")
                # $ grouptalk.add("주인공|^^")

            #elif day == 3 :
                # $ grouptalk.add("날짜|3월 11일 수요일")
                # $ grouptalk.add("주인공|엌ㅋㅋㅋㅋ 내일 동아리 첫 정기연습이다...두근두근 거리는데?")
                # $ grouptalk.add("동삼용|뭐 뻔대 너는 경력있는 신입인데 걱정할 필요 없지 않아?")
                # $ grouptalk.add("박대현|진짜 삼용이 너는 외특인데 그런 용어들은 어디서 배우는거냐...")
                # $ grouptalk.add("오덕현|큿..어째서 와타시보다 인터넷 용어를 더 많이 알고 있냐는...!")
                # $ grouptalk.add("동삼용|?? 그냥 주변에 있던 다른 친구들이 많이 알려주던데?")
                # $ grouptalk.add("해장중|워우...역시 인맥킹...")
                # $ grouptalk.add("김진일|ㅋㅋㅋㅋㅋㅋㅋㅋ 걱정하지 말고 편하게 지르고 와라!")
                # $ grouptalk.add("연속|다음에 나랑도 노래방 한 번 가자! 내 노래를 들려줄게 ㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|오 진일이 노래 실력도 기대하면 되는 부분?")
                # $ grouptalk.add("유현재|오올~")
                # $ grouptalk.add("노미래|오올~~")
                # $ grouptalk.add("주인공|올오~~~")

            #elif day == 4 :
                # $ grouptalk.add("날짜|3월 12일 목요일")
                # $ grouptalk.add("주인공|으어어...목이 아프...다...")
                # $ grouptalk.add("동삼용|엥? 무슨일이야?")
                # $ grouptalk.add("주인공|오랜만에 노래불러서 그런가봐, 동아리 첫 연습 재밌더라")
                # $ grouptalk.add("주인공|작년에는 수험생 신분이라 밴드 같은거 못했으니...올해 한을 풀어야짘ㅋㅋㅋ")
                # $ grouptalk.add("장중 |옹 근데 설마 뒤풀이 간 건 아니지? 내일 총엠인데..??")
                # $ grouptalk.add("주인공|...ㅎ")
                # $ grouptalk.add("김진일|주량은 많이 마셔야 느는거니까. 좋은 선택이다 뻔대야 ㅋㅋㅋㅋ")
                # $ grouptalk.add("오덕현|난 우매한 너희들의 사고방식을 평생 못따라가겠다는..")
                # $ grouptalk.add("유현재|저 친구 진짜 인생 멋있게 사네...")
                # $ grouptalk.add("연속|음? 근데 장중아 너도 오늘 총엠 전야제인가 뭔가 하면서 마신다지 않았냐?")
                # $ grouptalk.add("해장중|...ㅎ")
                # $ grouptalk.add("노미래|어휴 화상들..")

            #elif day == 5 :
                # $ grouptalk.add("날짜|3월 13일 금요일")
                # $ grouptalk.add("김진일|생존자 손~?")
                # $ grouptalk.add("해장중|호ㅡㄴㄴㄴㄴㄴ...!")
                # $ grouptalk.add("김진일|응~ 넌 아니야~")
                # $ grouptalk.add("유현재|으어ㅓㅓㅓㅓㅓ 죽을ㄹ커같ㅌ다.")
                # $ grouptalk.add("김진일|허허...애들 다들 약하구만..ㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|뻔대는 어디 갔냐?")
                # $ grouptalk.add("동삼용|걔 오늘도 병샷하더니 정줄 놓은 것 같던데??")
                # $ grouptalk.add("노미래|주방에서 선배들이 치킨너겟 구워줬으니 먹으러 와!")
                # $ grouptalk.add("김진일|오오 오키오키")

            elif day == 6 :
                $ grouptalk.add("날짜|3월 14일 토요일")
                $ grouptalk.add("주인공|....난 분명히 잠실에서 지하철을 탔을진대...왜 왕십리냐...")
                $ grouptalk.add("동삼용|엌ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("김진일|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("오덕현|풉ㅋ풉ㅋ")
                $ grouptalk.add("박대현|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("주인공|아니 웃는건 괜찮은데 아무도 안 챙겨준거 실화냐..ㅠㅠ")
                $ grouptalk.add("동삼용|너 그래도 개찰구까지는 똑바로 걸어 갔었는데..? 그래서 괜찮은 줄 알고 갔지")
                $ grouptalk.add("유현재|ㅋㅋㅋㅋㅋㅋㅋ 뻔대 다사다난하네..")
                $ grouptalk.add("해장중|하 어제 그래도 빨리 죽어서 나름 빨리 잤을텐데 지하철에서 또 자냐..")
                $ grouptalk.add("김진일|ㅋㅋㅋㅋㅋㅋㅋㅋ약해 약해")
                $ grouptalk.add("연속|그래도 어제 그렇게 마신다고 고생했다")
                $ grouptalk.add("노미래|진짜 고생했어 ㅠㅜㅠㅜ")

        elif week == 3 :
            if day == 0 :
                $ grouptalk.add("날짜|3월 15일 월요일")
                $ grouptalk.add ("유현재|아 총엠에서 마신 술 아직도 안깬듯 ㅠㅠ")
                $ grouptalk.add ("노미래|그러게 조절하며 마시지 현재야아아아~~~ ㅠㅠㅠ")
                $ grouptalk.add ("안금지|얘들아 나 벌써 과제 나왔어…")
                $ grouptalk.add ("동삼용|맞아… 근데 총엠에서 선배들 과잠 조녜드라!")
                $ grouptalk.add ("박대현|헐 나도 그 생각!!! 우리도 얼른 맞췄으면 좋겠다!!! 과잠 가즈아~")
                $ grouptalk.add ("해장중|야 우리는 과잠 안맞추냐 뻔대야")
                $ grouptalk.add ("김진일|일해라 노예야 ㅋㅋ")
                $ grouptalk.add ("주인공|와 진짜 총엠 다녀오자마자 부려먹는다고? 하… 도비는 일해야지")

            elif day == 1 :
                $ grouptalk.add("날짜|3월 16일 화요일")
                $ grouptalk.add ("해장중|우리 그래서 과잠은 언제 맞추나여ㅕㅕㅕㅕㅕ")
                $ grouptalk.add ("김진일|과잠준비위원회라는 걸 따로 만드는게 좋지 않을까?")
                $ grouptalk.add ("박대현|오! 그게 좋을듯")
                $ grouptalk.add ("노미래|응응 그래야 뭐라도 진행될것 같아 ㅠㅠ")
                $ grouptalk.add ("동삼용|와 심리학과는 벌써 과잠 맞췄다는데??? 이거 봐봐 진짜 잘 맞췄다 ㅠㅠㅠ")
                $ grouptalk.add ("유현재|와 진짜 예쁘다… 우리도 그럼 얼른 과준위 만들자. 일단 그럼 미래랑 나 할래 ㅋㅋㅋ 또 하고싶은 분?")
                $ grouptalk.add ("동삼용|나나나나나나나나")
                $ grouptalk.add ("김진일|과잠 디자인이면 또 내가 나설 차례가 왔군")
                $ grouptalk.add ("해장중|오케이~ 뻔대야 너가 톡방 파")

            #elif day == 2 :
                # $ grouptalk.add ("박대현|연대 경영이랑 미팅할 남자분 빠르게 2분 모십니다")
                # $ grouptalk.add ("해장중|오오…. 자리 있음?")
                # $ grouptalk.add ("박대현|알콜 중독자 불가능")
                # $ grouptalk.add ("동삼용|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add ("주인공|나는 가능?")
                # $ grouptalk.add ("박대현|뻔대는 노예라서 불가능")
                # $ grouptalk.add ("유현재|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add ("주인공|와 진짜 너무하닼ㅋㅋㅋㅋㅋㅋ")

            #elif day == 3 :
                # $ grouptalk.add ("주인공|애들아, 우리가 진짜 개멋있는 과잠 만들듯 ㅋㅋㅋ")
                # $ grouptalk.add ("안금지|와 진짜 기대된다! 빨리 사고 싶다 ㅋㅋㅋ")
                # $ grouptalk.add ("박대현|오오 예시 나옴?? 뭐있어 ㅋㅋㅋ")
                # $ grouptalk.add ("김진일|야 내가 미는게 제일 멋있다 그걸로 하자 ㅋㅋㅋ")
                # $ grouptalk.add ("유현재|개궁금하다 ㅋㅋㅋ")
                # $ grouptalk.add ("주인공|기대해라 ㅋㅋㅋㅋ")

            #elif day == 4 :
                # $ grouptalk.add ("주인공|우리가 과잠 후보 3개 만들었는데, 올릴게 애들아")
                # $ grouptalk.add ("박대현|와 대박 진짜 빨리 올려줘 ㅋㅋㅋ")
                # $ grouptalk.add ("주인공|이미지 1(), 이미지 2(), 이미지 3()")
                # $ grouptalk.add ("해장중|아무리 봐도 내게 제일 예쁘다 ㅋㅋㅋ 3번 투표해라 애들아")
                # $ grouptalk.add ("김진일|멋하면 카모 아니냐 ㅋㅋㅋ 야상과잠 존멋이다 1번 투표해줘 ㅋㅋㅋ")
                # $ grouptalk.add ("동삼용|누가봐도 2번이 제일 예쁘다 ㅋㅋㅋ")
                # $ grouptalk.add ("안금지|어, 생각보다 별론데….?나 안사고 싶은데ㅠㅠ")
                # $ grouptalk.add ("주인공|애들아 최대한 빨리 투표 해주라!")
                # $ grouptalk.add ("노미래|ㅇㅋㅇㅋ")

            elif day == 5 :
                # (강제 선택한 경우)
                if gwazam_finished == True :
                    $ grouptalk.add("날짜|3월 20일 금요일")
                    $ grouptalk.add ("안금지|ㅠㅠ 나는 안 살래… 돈이 너무 없어 ㅠ")
                    $ grouptalk.add ("유현재|음…. 그래도 고생했어 과준위 ㅎㅎㅎ")
                    $ grouptalk.add ("노미래|맞아맞아 ㅠㅠㅠ")
                    $ grouptalk.add ("김진일|야 진짜 어떻게 이러지 ㅋㅋㅋㅋㅋ")
                    $ grouptalk.add ("박대현|에이....금지야ㅠㅠ 그래도 ㅠㅠ 첫 과잠인데 사자")
                # (투표 연장한 경우)
                else :
                    $ grouptalk.add("날짜|3월 20일 금요일")
                    $ grouptalk.add ("주인공|애들아 그래도 최대한 민주적으로 가려고 의견 수렴하니까 투표 빨리 해줘 ㅠㅠ 부탁할게!")
                    $ grouptalk.add ("김진일|빨리빨리 하자.")
                    $ grouptalk.add ("해장중|과잠위 고생했으니까 빨리 해주세요!!")
                    $ grouptalk.add ("동삼용|하오하오!")
                    $ grouptalk.add ("노미래|ㅋㅋㅋㅋ 근데 현재야 너 저거 잘 어울리겠는데?")
                    $ grouptalk.add ("유현재|ㅋㅋㅋㅋㅋㅋㅋ")
                    $ grouptalk.add ("박대현|아 진짜 나가서 연애질해라 ㅋㅋㅋㅋㅋ")
                    $ grouptalk.add ("노미래|근데 대현이 모쏠 실화냐??ㅋㅋㅋㅋ")
                    $ grouptalk.add ("박대현|야 아니야 ㅋㅋㅋㅋ 나 연애해봤어 ㅋㅋㅋㅋ 어이가 없다")
                    $ grouptalk.add ("김진일|ㅋㅋㅋㅋㅋ 니들이 사랑을 아냐? ")
                    $ grouptalk.add ("해장중|와 진일이 갬성 빼앰~~~ ")
                    # $ grouptalk.add ("SYSTEM | 투표 결과 1안 | 11 /  2안 | 8 / 3안 | 5")
                    # $ grouptalk.add ("SYSTEM | 투표를 연장하시겠습니까? Y/ N ")

            #elif day == 6 :
                # 강제 종료
                # if gwazam_finished == True :
                #     $ grouptalk.add ("해장중|술~ 이 한잔 생각 나~는 밤")
                #     $ grouptalk.add ("유현재|마치~ 있는 것 같아요~")
                #     $ grouptalk.add ("박대현|그~ 좋았던 시~절들")
                #     $ grouptalk.add ("노미래|이젠 모~두 한숨만 되네요~")
                #     $ grouptalk.add ("김진일|??? 다들 갑자기 왜이래… 장중이 술 땡기면 ㄱㄱ?")
                #     $ grouptalk.add ("해장중|이거 노래임 ㅋㅋㅋ")
                #     $ grouptalk.add ("동삼용|오 이거 무슨 노래야???")
                #     $ grouptalk.add ("주인공|임창정의 소주한잔!!!")

                # 투표 할 시에
                # else :
                #     $ grouptalk.add ("주인공|근데 님들아 투표좀~~~~")
                #     $ grouptalk.add ("동삼용|투표 가즈아~!!!!")
                #     $ grouptalk.add ("김진일|아직도 B가 안될거라고 생각하는 흑두루미들 없재?")
                #     $ grouptalk.add ("박대현|자하연 물 온도 몇도냐 ㅋㅋㅋㅋㅋㅋ")
                #     $ grouptalk.add ("노미래|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                #     $ grouptalk.add ("유현재|ㅋㅋㅋㅋㅋㅋ")

        elif week == 4 :
            #if day == 0 :
                # 투표 강제 종료시
                # if gwazam_finished == True :
                #     $ grouptalk.add ("박대현|우리 과잠은 언제 나오지??")
                #     $ grouptalk.add ("주인공|아마 곧 나올 것 같은데 ㅋㅋㅋ 우리 과잠 진짜 예쁜 것 같아!")
                #     $ grouptalk.add ("안금지|아닌 것 같은데….ㅠ")
                #     $ grouptalk.add ("김진일|에이 입어보면 다르다 진짜 ㅋㅋㅋ")
                #     $ grouptalk.add ("노미래|그래 ㅋㅋㅋ 예뻐도 안 예뻐도 우리가 같이 입는게 의미가 있지")
                #     $ grouptalk.add ("유현재|역시 미래다 ㅋㅋㅋㅋ")
                #     $ grouptalk.add ("해장중|으~ 진짜 너네 적당히해라")
                #     $ grouptalk.add ("유현재|싫은데 싫은데???ㅋㅋㅋㅋ")

                # 투표 진행시
                # else :
                #     $ grouptalk.add ("김진일|역시 내게 제일 멋있네, b안이 제일 높네")
                #     $ grouptalk.add ("해장중|투표 실화냐….")
                #     $ grouptalk.add ("유현재|저걸 어떻게 입냐 ㅠㅠ")
                #     $ grouptalk.add ("동삼용|애들아 a안 밀면 b안 이길 수 있어, 영차영차 외치자!, 영")
                #     $ grouptalk.add ("박대현|차")
                #     $ grouptalk.add ("박대현|영")
                #     $ grouptalk.add ("해장중|차")
                #     $ grouptalk.add ("김진일|영차한다고 되겠다 ㅉㅉ")
                #     $ grouptalk.add ("주인공|에이 진일아~")

            #elif day == 1 :
                # 투표 종료시
                # if gwazam_finished == True :
                #     $ grouptalk.add ("주인공|애들아 우리 이제 우리끼리도 밥약하자 ㅋㅋㅋ")
                #     $ grouptalk.add ("동삼용|오 또 뻔대가 일한다 ㅋㅋㅋㅋ 나 완전 좋아 ㅋㅋㅋ 나는 이번주 월,화, 수, 목 12시 반 가능해")
                #     $ grouptalk.add ("해장중|나도나도 ㅋㅋㅋㅋ 근데 나는 화, 수만 학교 와서 ㅋㅋㅋ 그때만 될 것 같아")
                #     $ grouptalk.add ("김진일|와 장중이 주2 실화야??? 수요일 저녁에 출국하면 4박 5일로 여행가겠다 ㅋㅋㅋ")
                #     $ grouptalk.add ("유현재|ㅋㅋㅋㅋ 미래랑 나도 갈까? 갈 수 있을 것 같아")
                #     $ grouptalk.add ("박대현|수 ㄱㄱㄱㄱ, 장중이 엄마한테 18학점이라고 하고, 절반 등록금깡한거 아니야?")
                #     $ grouptalk.add ("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")

                # 투표 지속시
                # else :
                #     $ grouptalk.add ("김진일|애들아 곧 24일에 투표 마감인데 투표 아직 안한 사람은 해줘!")
                #     $ grouptalk.add ("주인공|지금까지 투표 안하면 뻔대가 곤란하다는게 학계의 정설")
                #     $ grouptalk.add ("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                #     $ grouptalk.add ("동삼용|과준위가 힘빠진다는 것도 유력한 가설")
                #     $ grouptalk.add ("박대현|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                #     $ grouptalk.add ("유현재|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                #     $ grouptalk.add ("노미래|빨리 해주자 애들아 ㅋㅋㅋㅋ")
                #     $ grouptalk.add ("주인공|저녁까지 안해주시면 갠톡들어갑니다~")

            if day == 2 :
            #   투표 마감시
                if gwazam_finished == True :
                    $ grouptalk.add("날짜|3월 24일 화요일")
                    $ grouptalk.add ("유현재|우리 과잠은 언제오지 ㅋㅋㅋ 빨리 입고 싶은데")
                    $ grouptalk.add ("김진일|ㅋㅋㅋ 진짜 간지다 누가 봐도 눈에 띌듯 ㅋㅋㅋㅋ")
                    $ grouptalk.add ("안금지|그게 문제지….ㅠㅠ")
                    $ grouptalk.add ("주인공|에이 아직 안 입어봤는데 그러지 말자 ㅋㅋㅋㅋ")
                    $ grouptalk.add ("해장중|우리 내일 점모 맞지?")
                    $ grouptalk.add ("박대현|뭐 먹지?? 중국음식?")
                    $ grouptalk.add ("동삼용|헐… 개좋아")
                    $ grouptalk.add ("주인공|ㅋㅋㅋㅋ 삼용이 배려로 내일은 중식먹자!")
                    $ grouptalk.add ("유현재|좋아!!")

            # 투표 지속시
                else :
                    $ grouptalk.add("날짜|3월 24일 화요일")
                    $ grouptalk.add ("주인공|오늘이 투표 마지막 날입니다! 예쁜 과잠을 선택해주세요~")
                    $ grouptalk.add ("해장중|진짜 과준위 4일동안 회의하고 정한 과잠입니다ㅠ 여러분 투표 부탁드려요!")
                    $ grouptalk.add ("김진일|그래 애들아 투표 좀 해라")
                    $ grouptalk.add ("동삼용|지금 투표하면 내가 원하는 걸로 할 수 있어 애들아!!!")
                    $ grouptalk.add ("안금지|음…..")
                    $ grouptalk.add ("박대현|나는 했어 과준위 ㅠㅠ 너무 고생한다 애들아 투표하자!!")
                    $ grouptalk.add ("주인공| 고마워 다들 ㅋㅋㅋㅋ 다들 후보들이 너무 예뻐서 고민하는거지 뭐 ㅋㅋㅋ 내가 봐도 어렵다 ㅋㅋㅋ 여튼 저녁까지는 투표 마감할게요! ")


            elif day == 3 :
                $ grouptalk.add("날짜|3월 25일 토요일")
                $ grouptalk.add ("해장중|이제 과잠바는 해결됬겠다 뻔엠 ㄱㄱ?")
                $ grouptalk.add ("유현재|헐 맞다 우리 뻔엠도 가야되지??")
                $ grouptalk.add ("해장중|ㅋㅋㅋㅋ 다들 까먹고 있었나 보네")
                $ grouptalk.add ("김진일|에이~ 우리끼리 술마시는 행사인데 어떻게 까먹어 ㅋㅋㅋ")
                $ grouptalk.add ("동삼용|와 우리 뻔엠도 가?? 과잠 맞추자마자 뻔엠 계획도 세우고 이번학기 개잼!!!")
                $ grouptalk.add ("박대현|가즈아~~!")
                $ grouptalk.add ("노미래| 행사가 끊임없닼ㅋㅋㅋㅋ 넘좋아!")

            #elif day == 4 :
                # $ grouptalk.add ("주인공|그럼 우리 내일 뻔엠 날짜 정할래??")
                # $ grouptalk.add ("해장중|말 나온김에 지금 어때?!!!")
                # $ grouptalk.add ("노미래|현재가 오늘 바빠서 카톡을 못볼 것 같아서...ㅠㅠ 오늘 말해놓고 내일 정하는게 좋을 것 같아 ")
                # $ grouptalk.add ("해장중|아 ㅇㅋㅇㅋ")
                # $ grouptalk.add ("동삼용|ㅇㅋㅇㅋ가 무슨 뜻이야??")
                # $ grouptalk.add ("김진일|아 맞다 얘 중국에서 왔지 ㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add ("노미래|ㅋㅋㅋㅋ ㅇㅋㅇㅋ  = 오키오키! 알았다는 말이야 ㅋㅋㅋ")
                # $ grouptalk.add ("동삼용|아하!")
                # $ grouptalk.add ("박대현|앞으로도 모르는 말 있으면 물어봐 삼용쓰 ㅋㅋㅋ")
                # $ grouptalk.add ("동삼용|ㅇㅋㅇㅋ")
                # $ grouptalk.add ("주인공|얘들아 뻔엠 날짜 내일 정하는 걸로 한다??")
                # $ grouptalk.add ("동삼용|ㅇㅋㅇㅋ")
                # $ grouptalk.add ("박대현|굿굿")


            elif day == 5 :
                $ grouptalk.add("날짜|3월 27일 금요일")
                $ grouptalk.add ("주인공|얘들아 우리 뻔엠 언제 갈래?!!!!")
                $ grouptalk.add ("해장중|뻔엠!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!")
                $ grouptalk.add ("박대현|다들 언제가 좋아??")
                $ grouptalk.add ("유현재|주중에는 수업이 있으니까 금,토 아니면 토,일??")
                $ grouptalk.add ("노미래|져아져아~")
                $ grouptalk.add ("동삼용|나도 좋아!!")
                $ grouptalk.add ("주인공|중간고사 전에 가는게 좋으니까 다음주 금,토로 정하는게 어때??")
                $ grouptalk.add ("김진일|콜")
                $ grouptalk.add ("동삼용|콜")
                $ grouptalk.add ("해장중|콜")
                $ grouptalk.add ("박대현|쿨")
                $ grouptalk.add ("유현재|꿀")
                $ grouptalk.add ("노미래|꿀꿀")
                $ grouptalk.add ("김진일|그만해라~")

            elif day == 6 :
                $ grouptalk.add("날짜|3월 28일 토요일")
                $ grouptalk.add ("동삼용|우리 근데 뻔엠 전에는 과잠 오겠지??")
                $ grouptalk.add ("해장중|으아아아아 과잠 기대된다!!!")
                $ grouptalk.add ("김진일|ㅋㅋㅋ 좀 기다려 이 과잠무새들아 어떻게든 되겠지")
                $ grouptalk.add ("안금지|난 과잠 주문 안했는데 ㅎㅎ")
                $ grouptalk.add ("노미래|응??? 왜 주문 안했어 ㅠㅠㅠㅠ")
                $ grouptalk.add ("안금지|그냥 그렇게 됐어 ㅋㅋㅋ")
                $ grouptalk.add ("노미래|지금이라도 주문해 ㅠㅠㅠ")
                $ grouptalk.add ("안금지|그럴까??")
                $ grouptalk.add ("박대현|?")
                $ grouptalk.add ("동삼용|이미 주문 들어가서 그건 안될것 같아…")
                $ grouptalk.add ("유현재|ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ 까비…")

    elif month == 4 :
        if week == 1 :
            #if day == 0 :
                # $ grouptalk.add("날짜|4월 1일 일요일")
                # $ grouptalk.add("주인공|아...대학 와서 첫 만우절인데 일요일인거 실화냐...")
                # $ grouptalk.add("오덕현|나 오늘부터 탈덕하기로 결심했어!")
                # $ grouptalk.add("연속|얘들아 만약에 내가 애니메이션 같은 걸 보면 때려줘..")
                # $ grouptalk.add("해장중|나도 오늘부터 금주하기로 결심했다!")
                # $ grouptalk.add("연속|대학와서 한 달동안 술밖에 안 마신거 같아서.. 내 건강을 위해서라도 술을 끊기로 함")
                # $ grouptalk.add("박대현|나 솔로 탈출함 ㅅㄱ")
                # $ grouptalk.add("노미래|와...진짜 노답들이다 이건...")
                # $ grouptalk.add("유현재|내말이...")
                # $ grouptalk.add("김진일|날짜만 빼고 박제해두면 되는각 아니냐?")
                # $ grouptalk.add("오덕현|야..야메룽다~~!")
                # $ grouptalk.add("유현재|(그만둬란 뜻이다.)")
                # $ grouptalk.add("안금지|난 오늘부터 공부 열심히 해야지~")
                # $ grouptalk.add("주인공|넌 진짜 열심히 하고있잖아 ㅋㅋㅋㅋ")

            if day == 1 :
                $ grouptalk.add("날짜|4월 2일 월요일")
                $ grouptalk.add("주인공|공지하나만 할게요~")
                $ grouptalk.add("주인공|얘들아 뻔엠이 이번주 금토인건 알지?")
                $ grouptalk.add("주인공|엠준위에서 회의한 결과 되는 장소가 두 군데 나왔어!")
                $ grouptalk.add("주인공|멀지만 조금 싼 대별리랑, 가깝지만 조금 비싼 신숲!!")
                $ grouptalk.add("주인공|둘 중에 어디가 좋을지 투표 부탁해~ 겸사겸사 엠티비와 장발후발 투표도 받을게!")
                $ grouptalk.add("주인공|장소와 가격의 경우에는 시간이 많이 안 남았기 때문에")
                $ grouptalk.add("주인공|내일까지 빠르게 투표해줘~!")
                $ grouptalk.add("김진일|엠티는 당연히 대별리 아니겠냐~ 신숲은 무슨;;")
                $ grouptalk.add("해장중|그거 ㄹㅇ 인정~ 가까우면 술 마시다 다 도망치겠다")
                $ grouptalk.add("연속|그러니 님들 대별리 ㄱㄱ")
                $ grouptalk.add("동삼용|ㄴㄴㄴ 저번에 대별리 갔다가 뻔대 친구 2호선 한 바퀴 도는 거 못봤어?")
                $ grouptalk.add("연속|그런 걸 방지하기 위해서라도 가까운 곳이 최고다~ 이 말이야")
                $ grouptalk.add("박대현|ㅋㅋㅋㅋㅋ음 어디로 가지...")
                $ grouptalk.add("안금지|엠티비 2만원부터인 건 너무 비싼거 아냐??;;;")

            #elif day == 2 :
                # $ grouptalk.add("날짜|4월 3일 화요일")
                # #(강제 종료 한 경우)
                # $ grouptalk.add("주인공|자 투표 결과 장소는 (선택) 엠티비는 (선택)으로 결정되었습니다!")
                # $ grouptalk.add("주인공|시간이 별로 없으니 생협 123-456-789102 여기로 빠르게 엠티비 보내주세요~")
                # $ grouptalk.add("안금지|아..나 돈 별로 없는데...")
                # $ grouptalk.add("해장중|오키오키~보내드림")
                # $ grouptalk.add("유현재|나쁘지는 않네 ㅋㅋㅋㅋ 뻔엠 너무 기대된다")
                # $ grouptalk.add("노미래|가서 또 재밌게 놀자 현재야 ㅎㅎ")
                # $ grouptalk.add("오덕현|송.금. 해버렸다...")
                # $ grouptalk.add("동삼용|그리고 엠준위에서 열심히 프로그램들 짜고 있으니까 기대해도 좋을걸??")
                # $ grouptalk.add("박대현|오옹 기대할겤ㅋㅋㅋ")
                # #(연장 경우)
                # $ grouptalk.add("주인공|투표 마감 오늘까지입니다~ 최대한 의견 반영하려고 하니까 많이 참여해줘!!")
                # $ grouptalk.add("김진일|대별리 고다고~ 산택가기도 좋고 별도 예쁘고 얼마나 좋아")
                # $ grouptalk.add("해장중|대 별 리 대 별 리")
                # $ grouptalk.add("동삼용|신 숲 신 숲")
                # $ grouptalk.add("주인공|장발후발 투표도 잊지 말아요~")
                # $ grouptalk.add("박대현|아;;; 미안 나 그날 갑자기 약속 생겨서 장발 못할듯 ㅈㅅㅈㅅ ㅠㅜ")
                # $ grouptalk.add("주인공|아 ㅠㅜㅠㅜ 어쩔 수 없지 뭐..ㅠㅜ")
                # $ grouptalk.add("SYSTEM|장소 투표 결과 대별리 10 / 신숲 10")
                # $ grouptalk.add("SYSTEM|투표가 동률이 나왔습니다. 당신은 무엇을 선택하겠습니까?")
                # $ grouptalk.add("SYSTEM|장발후발 투표 결과 장발대 9 / 후발대 11")
                # $ grouptalk.add("SYSTEM|투표를 연장하시겠습니까? Y / N")

            #elif day == 3 :
                # $ grouptalk.add("날짜|4월 4일 수요일")
                # $ grouptalk.add("주인공|자 투표 결과 장소는 (선택) 엠티비는 (선택)으로 결정되었습니다!")
                # $ grouptalk.add("주인공|시간이 별로 없으니 생협 123-456-789102 여기로 빠르게 엠티비 보내주세요~")
                # $ grouptalk.add("안금지|아..나 돈 별로 없는데...")
                # $ grouptalk.add("해장중|오키오키~보내드림")
                # $ grouptalk.add("유현재|나쁘지는 않네 ㅋㅋㅋㅋ 뻔엠 너무 기대된다.")
                # $ grouptalk.add("노미래|가서 또 재밌게 놀자 현재야 ㅎㅎ")
                # $ grouptalk.add("오덕현|송.금. 해버렸다...")
                # $ grouptalk.add("동삼용|그리고 엠준위에서 열심히 프로그램들 짜고 있으니까 기대해도 좋을걸??")
                # $ grouptalk.add("박대현|오옹 기대할겤ㅋㅋㅋ")
                # #(장발/후발 투표 마감시)
                # $ grouptalk.add("주인공|그리고 장발 지원해준 사람들 고마워!! ㅋㅋㅋㅋ 맛있는 거 많이 사봅시다!")
                # $ grouptalk.add("해장중|굿굿ㅋㅋㅋ 근데 뻔대야 일단 회식 왔으면 술이나 더 마셔")
                # $ grouptalk.add("김진일|인정 누가 술자리에서 폰하냐;;")
                # $ grouptalk.add("동삼용|인정 22222")
                # $ grouptalk.add("박대현|저 친구들 또 술 마시냐..")
                # #(마감 안했을 시)
                # $ grouptalk.add("주인공|장소와 가격은 투표 마감했지만, 장발/후발은 아직 안했으니 투표 계속 부탁해요!")
                # $ grouptalk.add("오덕현|큿..와타시...급작스러운 동아리 일정상 장발..못한달까..? 고멘...")
                # $ grouptalk.add("주인공|엌ㅋㅋㅠㅜ 아냐 어쩔 수 없지..ㅠㅜㅠㅜ 일정 잘 끝내고 오렴..")
                # $ grouptalk.add("해장중|뻔대야 잔이 비었다?")
                # $ grouptalk.add("김진일|회식 아직 안끝났다")
                # $ grouptalk.add("유현재|술 진짜 거의 매일같이 마시네;;")
                # $ grouptalk.add("SYSTEM|장발후발 투표 결과 장발대 8 / 후발대 14")
                # $ grouptalk.add("SYSTEM|투표를 연장하시겠습니까? Y / N")

            #elif day == 4 :
                # $ grouptalk.add("날짜|4월 5일 목요일")
                # #(마감 안 했을 시)
                # $ grouptalk.add("주인공|오늘이 장발후발 마감날입니다!! 내일 뻔엠이니까 빠른 투표 고다고~")
                # $ grouptalk.add("유현재|저 뻔대야..미안한데..")
                # $ grouptalk.add("연속|그날 장발 못할 것 같아 ㅠㅜㅠㅜ")
                # $ grouptalk.add("노미래|나도..ㅠㅜㅠㅜ 갑자기 가족 행사가 잡혀서")
                # $ grouptalk.add("주인공|어..ㅜㅠㅜㅠㅜ 어쩔 수 없지..ㅠㅜㅠ")
                # $ grouptalk.add("동삼용|둘이 동시에 못오는 거 설마..?")
                # $ grouptalk.add("유현재|에이 아냐;; 설마 일하기 싫어서 이러겠냐..")
                # $ grouptalk.add("노미래|맞아 진짜 일 생겨서 그런거야 ㅠㅜㅠㅜ")
                # $ grouptalk.add("주인공|일단 ㅇㅋ...")
                # $ grouptalk.add("SYSTEM|장발후발 투표 결과 장발대 6 / 후발대 18")
                # $ grouptalk.add("SYSTEM|투표가 종료되었습니다.")
                # #(투표 마감 했을시)
                # $ grouptalk.add("주인공|으아아아아 드이어 내일 뻔엠!!!")
                # $ grouptalk.add("동삼용|마셔마셔!! 먹고 뒤져!!")
                # $ grouptalk.add("유현재|와..선배들 없이 엠티라니")
                # $ grouptalk.add("노미래|기분 진짜 묘하다")
                # $ grouptalk.add("김진일|뭐 선배들 없으니까 더 편하게 마실 수 있지 않겠냨ㅋㅋ")
                # $ grouptalk.add("오덕현|살짝..코와이 하달..까?")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋ 그냥 편하게 마시고 재밌게 놀다오자!")
                # $ grouptalk.add("주인공|굿굿")

            #elif day == 5 :
                # $ grouptalk.add("날짜|4월 6일 금요일")
                # $ grouptalk.add("주인공|생존...신고...하하핳...얘들아..우리..이러다가...아 몰라 귀찮다")
                # $ grouptalk.add("해장중|하하하하하하하하하하ㅏ핳ㅎ하하하하하하")
                # $ grouptalk.add("동삼용|에엘에에레베레 술 들어 가나다ㅏㅏㅏㅏ다다")
                # $ grouptalk.add("오덕현|쿠쿠쿠쿸ㅋ쿠쿸쿠ㅜㅋ")
                # $ grouptalk.add("노미래|현재야 사랑해 ♡♥")
                # $ grouptalk.add("유현재|나도 미래양 ♥♡")
                # $ grouptalk.add("김진일|다들 약해빠져서는 에잉 ㅉㅉ. 근데 여기가 어디지?")
                # $ grouptalk.add("박대현|흐흐흐그그그흐흐흐 ㅠㅜㅜㅜ우ㅜㅜ")
                # $ grouptalk.add("주인공|편하게 마시기는 개..뿔...")

            elif day == 6 :
                $ grouptalk.add("날짜|4월 7일 토요일")
                $ grouptalk.add("주인공|후...이제 진짜..이렇게는 안마시낟")
                $ grouptalk.add("해장중|으음 이제 필끊이 너무 자연스러워졌다;;")
                $ grouptalk.add("김진일|ㅉㅉㅉ 약골 자식들")
                $ grouptalk.add("동삼용|그래서 어제 혼자 미아된 사람이 누구더라?")
                $ grouptalk.add("김진일|쉿")
                $ grouptalk.add("노미래|현재야 괜찮아..?")
                $ grouptalk.add("유현재|으으 머리 너무 아프다..")
                $ grouptalk.add("오덕현|으으 와타시도...저렇게 위로해줄 카노조..가 필요하다는..")
                $ grouptalk.add("박대현|포기해..포기하면 편해")
                $ grouptalk.add("주인공|여튼 다들 뻔엠 너무 고생했고..내일은 푹 쉬고 월요일에 보자")
                $ grouptalk.add("해장중|ㅇㅋㅇㅋ")
                $ grouptalk.add("동삼용|ㅇㅋㅇㅋ")

        elif week == 2 :
            #if day == 0 :
                # $ grouptalk.add("날짜|4월 8일 일요일")
                # $ grouptalk.add("해장중|흐음 그래도 집와서 푹 자니까 좀 괜찮아진 것 같은데")
                # $ grouptalk.add("동삼용|역시 해장에는 잠인가")
                # $ grouptalk.add("해장중|그런 의미로 술 드실분?")
                # $ grouptalk.add("주인공|저 알콜중독자 자식..")
                # $ grouptalk.add("박대현|장중아 너 이거 한 번 해봐라 #알코올 중독 검사")
                # $ grouptalk.add("해장중|어, 그거 이미 했는데 평범한 새내기는 무조건 중독자던데?")
                # $ grouptalk.add("동삼용|엌ㅋㅋㅋ저거 뭐임 나도 해봐야지..")
                # $ grouptalk.add("김진일|뭔데 저거;;")
                # $ grouptalk.add("동삼용|....위험군 실화냐..")
                # $ grouptalk.add("주인공|...나도")
                # $ grouptalk.add("안금지|? 난 아니던데??")
                # $ grouptalk.add("노미래|어휴 이 술쟁이들 적당히 마셔;;;")
                # $ grouptalk.add("김진일|아닐거라 생각하는 당신도 Hoxy..?")

            if day == 1 :
                $ grouptalk.add("날짜|4월 9일 월요일")
                $ grouptalk.add("동삼용|님들 그거 앎?")
                $ grouptalk.add("박대현|???? 뭐가?")
                $ grouptalk.add("유현재|뭐가?")
                $ grouptalk.add("동삼용|다다음주부터 중간고사 시즌임")
                $ grouptalk.add("주인공|엌ㅋㅋㅋㅋㅋㅋㅋ 진짜네;;;")
                $ grouptalk.add("김진일|와 뭐했다고 벌써 시험이냐..;;")
                $ grouptalk.add("노미래|ㅠㅜㅠㅜㅠ 대학 왔다고 시험이 끝이 나는게 아니구나..")
                $ grouptalk.add("유현재|그러게 ㅠㅜㅠㅜ 미래야 그래도 우린 서로 힘내서 같이 공부하자")
                $ grouptalk.add("노미래|꺄 좋아 현재야~")
                $ grouptalk.add("오덕현|쿠...이래서 커플들은..크흡..")
                $ grouptalk.add("해장중|그런 건 갠톡에서 해라 이 자식들아~ 아 근데 다음 주 축제인 것도 알지??")
                $ grouptalk.add("연속|게스트 누구오려나..? 축제면 당연히 술도 마셔야지?? ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("주인공|해또술. 해장중 또 술얘기.")
                $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋ")

            #elif day == 2 :
                # $ grouptalk.add("날짜|4월 10일 화요일")
                # $ grouptalk.add("해장중|님들 혹시 드랍지 어떻게 뽑는지 앎?")
                # $ grouptalk.add("동삼용|드랍지가 뭐임?")
                # $ grouptalk.add("박대현|수강신청취소원이라고 이미 신청한 강의 취소하는 거야")
                # $ grouptalk.add("동삼용|ㅇㅎ...애들이 자꾸 드랍럭스미아 드랍럭스미아 하는데 그게 그 뜻이었구나")
                # $ grouptalk.add("유현재|엌ㅋㅋㅋㅋㅋ드랍럭스미앜ㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|아마 학교 홈페이지 들어가서 찾아보면 있을걸?")
                # $ grouptalk.add("주인공|왜 뭐 드랍하게??")
                # $ grouptalk.add("해장중|나의 숙취에 찌든 뇌가 오전수업은 아니라고 자꾸 말해서 ^^")
                # $ grouptalk.add("노미래|ㅋㅋㅋㅋㅋㅋㅋㅋㅋ너무 당연했다..")
                # $ grouptalk.add("김진일|장중이 저 자식 결국 날 버리고 가는구나 이제 누구랑 같이 듣냐~")
                # $ grouptalk.add("해장중|너도 드랍 ㄱㄱ 빠드익선이랬음.")
                # $ grouptalk.add("동삼용|빠드익선?")
                # $ grouptalk.add("유현재|드랍은 빠르면 빠를수록 이득이다..")
                # $ grouptalk.add("동삼용|ㅇㅎㅇㅎㅇㅎ")
                # $ grouptalk.add("김진일|일단은 고려해볼게 ㅋ")

            #elif day == 3 :
                # $ grouptalk.add("날짜|4월 11일 수요일")
                # $ grouptalk.add("주인공|으아아아아아 심심해!!")
                # $ grouptalk.add("해장중|그니까~~ 뭔가 행사같은거 없으니까 너무 심심함~~")
                # $ grouptalk.add("동삼용|중간고사 있는데?")
                # $ grouptalk.add("해장중|으아아아아어앙아아아아 그만해~~")
                # $ grouptalk.add("오덕현|우리들의 HP는 이미 0이라굿! 다메다!!")
                # $ grouptalk.add("동삼용|(하지 말라는 뜻이다)")
                # $ grouptalk.add("김진일|심심한 사람들 심심할 때는 간맥이지 ㄱ?")
                # $ grouptalk.add("해장중|ㄱ")
                # $ grouptalk.add("주인공|ㄱㄱㄱ")
                # $ grouptalk.add("노미래|너희는 술 아니면 할 것도 없니?")
                # $ grouptalk.add("유현재|그니깐, 진짜 할 거 없나 보구나")
                # $ grouptalk.add("박대현|커플들이 할 얘기냐!!")
                # $ grouptalk.add("주인공|죽창 들어!!! ㅂㄷㅂㄷ")

            #elif day == 4 :
                # $ grouptalk.add("날짜|4월 12일 목요일")
                # $ grouptalk.add("주인공|쿵쿵짝")
                # $ grouptalk.add("해장중|쿵쿵짝")
                # $ grouptalk.add("동삼용|we will we will rock you!!")
                # $ grouptalk.add("김진일|rock you!!")
                # $ grouptalk.add("오덕현|모임;; 대체 모임;;;")
                # $ grouptalk.add("박대현|아 설마 저 친구들..")
                # $ grouptalk.add("주인공|마마~~~")
                # $ grouptalk.add("해장중|우우우우~~~")
                # $ grouptalk.add("동삼용|마마~~~")
                # $ grouptalk.add("김진일|갈릴레오, 갈릴레오, 갈릴레오 피가로~~")
                # $ grouptalk.add("유현재|세상에나..뭘 보고 온거야...")
                # $ grouptalk.add("안금지|;;못 따라가겠어..;;")

            #elif day == 5 :
                # 과 중간점검 스크립트?
                # $ grouptalk.add("날짜|4월 13일 금요일")
                # $ grouptalk.add("주인공|불금에는 야식~")
                # $ grouptalk.add("박대현|야식에는 치킨~")
                # $ grouptalk.add("해장중|치킨에는 맥주~")
                # $ grouptalk.add("김진일|맥주에는 소주~")
                # $ grouptalk.add("오덕현|사케에는 간빠이~!")
                # $ grouptalk.add("주인공|간빠이!")
                # $ grouptalk.add("박대현|치얼스!")
                # $ grouptalk.add("해장중|건배!")
                # $ grouptalk.add("노미래|그래서 결국 야식으로 치킨에 소맥을 먹는다는 거지?")
                # $ grouptalk.add("유현재|오 나 미래랑 같이 가도 됨?? 어디서 먹고 있음??")
                # $ grouptalk.add("주인공|낙성대학교 근처 글로벌 하우스로 오면 됨 ㅋㅋㅋㅋ")
                # $ grouptalk.add("노미래|오키오키 그래도 가깝네 현재랑 같이 갈게")
                # $ grouptalk.add("동삼용|옹 나도 갈게~")

            #elif day == 6 :
                # $ grouptalk.add("날짜|4월 14일 토요일")
                # $ grouptalk.add("주인공|아무리 생각해도 주말은 최고인거 같아")
                # $ grouptalk.add("동삼용|ㄹㅇ 오랜만에 낮잠 잤다 ㅋㅋㅋㅋ")
                # $ grouptalk.add("오덕현|휴식! 게이무! 밀린 명작! 사이코!!")
                # $ grouptalk.add("해장중|오오 생각해보니까 이틀 뒤에 축제잖아? 기대기대")
                # $ grouptalk.add("김진일|그래서 게스트로는 누구옴?")
                # $ grouptalk.add("안금지|우리학교 축제 재미없다고 그러던데;;")
                # $ grouptalk.add("유현재|에이 아직 한 번도 안 가봤는데 벌써부터 그런 말하기는 좀 그렇지")
                # $ grouptalk.add("노미래|맞아맞아 그래도 가보자!! ㅋㅋㅋ")
                # $ grouptalk.add("동삼용|좋아좋아!!")
                # $ grouptalk.add("주인공|그리고..축제의 뜻은..중간..고...")
                # $ grouptalk.add("해장중|그만.")
                # $ grouptalk.add("주인공|ㅇㅋ.")

        elif week == 3 :
            #if day == 0 :
                # $ grouptalk.add("날짜|4월 15일 일요일")
                # $ grouptalk.add("동삼용|오 대박 이번 축제 게스트로 소란온대!")
                # $ grouptalk.add("해장중|..? 수란?")
                # $ grouptalk.add("김진일|소란...?")
                # $ grouptalk.add("주인공|오오오오오오오오오 대박대박!!")
                # $ grouptalk.add("주인공|?? 근데 삼용아 너 외특인데 소란은 어떻게 아는겨??")
                # $ grouptalk.add("동삼용|친구가 추천해줘서 노래 몇 곡 들어봤는데 좋아서 기억하고 있었음 ㅋㅋㅋ")
                # $ grouptalk.add("해장중|?? 그래서 소란이 누구임?")
                # $ grouptalk.add("김진일|소란 피우지나 마 이 쉬키드라~")
                # $ grouptalk.add("주인공|아...제발...")
                # $ grouptalk.add("오덕현|대한민국의 밴드, 인디, 싱어송라이터. ‘좋은 음악은 결국 알아본다.’라는 단순한 믿음과 배짱으로 듣기 쉬우면서도 마음으로 기억되는 음악을 추구하는 밴드 (출처 : 꺼라위키)")
                # $ grouptalk.add("노미래|오옹 나 이 사람들 노래 조금 들어봤는데 진짜 좋았어")
                # $ grouptalk.add("유현재|좋아좋아 같이 구경가자 ^^")
                # $ grouptalk.add("주인공|ㅋㅋㅋㅋ 난 전집 다 듣고 유튭영상도 봤는데 라이브도 잘하심")
                # $ grouptalk.add("주인공|보면 후회 안 할거얔ㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|ㅇㅋ 너만 믿고 가본다")

            #elif day == 1 :
                # $ grouptalk.add("날짜|4월 16일 월요일")
                # $ grouptalk.add("주인공|고마워! 예쁘게 웃으며 얘길해줘서~")
                # $ grouptalk.add("동삼용|내 고백을 받아줘서~")
                # $ grouptalk.add("해장중|에블바리 춤!")
                # $ grouptalk.add("유현재|와아아아아아아악")
                # $ grouptalk.add("노미래|와 그래도 진짜 너무 재밌었다! ㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|역시 뻔대가 추천할만한 밴드였어")
                # $ grouptalk.add("해장중|진짜 ㄹㅇ 음원도 찾아들어봐야겠다.")
                # $ grouptalk.add("연속|오늘 부른 노래가 어떤 거 있었지??")
                # $ grouptalk.add("주인공|일단 <가을목이>랑 <살빼지마요>랑 <너를공부해>랑 음..")
                # $ grouptalk.add("동삼용|내가 갠톡으로 보내줄게 ㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|오오 감사감사~")
                # $ grouptalk.add("박대현|나도 보내줘 ㅋㅋㅋㅋ")
                # $ grouptalk.add("동삼용|ㅇㅋㅇㅋ")
                # $ grouptalk.add("주인공|하 그래도 라이브 진짜 너무 좋았다...크")
                # $ grouptalk.add("주인공|보컬분 입담도 진짜 너무 재밌었고 ㅋㅋㅋ")
                # $ grouptalk.add("동삼용|감상은 거기까지하고..당장 다음주부터 시험인거 잊지말자..ㅠㅜ")
                # $ grouptalk.add("김진일|윽...")

            if day == 2 :
                $ grouptalk.add("날짜|4월 17일 화요일")
                $ grouptalk.add("해장중|으음...대학이라고 해서 시험공부는 다를바가 없구나")
                $ grouptalk.add("연속|오히려 고등학교 때 보다 암기가 더 늘어난 것 같기도 하고?")
                $ grouptalk.add("김진일|그거 전부 너가 평소에 술만 마셔서 그런거 아니냐??")
                $ grouptalk.add("해장중|...할 말이 없습니다..")
                $ grouptalk.add("박대현|..장중아 지금 손에 들고 있는 맥주캔은 놓고 말하자")
                $ grouptalk.add("해장중|...그..만...")
                $ grouptalk.add("주인공|?? 그만하라고?")
                $ grouptalk.add("해장중|...그...치..만..!! 이렇게라도 하지 않으면..도모다치쿤! 나한텐 관심도 없는 걸!!")
                $ grouptalk.add("오덕현|손나 바카나!! 그럴 리 없잖아!! 넌 내 하나뿐인 시험 동지인걸!!")
                $ grouptalk.add("해장중|에에? 혼또??")
                $ grouptalk.add("오덕현|혼또니 혼또!")
                $ grouptalk.add("노미래|....시험 기간이라 다들 어딘가 이상해..")

            #elif day == 3 :
                # $ grouptalk.add("날짜|4월 18일 수요일")
                # $ grouptalk.add("주인공|시리어스 게임은 진지한 게임, 게임인데 진지...사회적 메시지를")
                # $ grouptalk.add("주인공|담고 있어야 하며, 그럼에도 게임이라서..에벱 에베벱")
                # $ grouptalk.add("해장중|뻔대쿤, 뻔대쿤도 비-루 한 캔 하싈?")
                # $ grouptalk.add("오덕현|손나! 그 캐-릭터는 와타시의 모노다!!")
                # $ grouptalk.add("주인공|안 할 거야..마시면 답도 없을 것 같아..")
                # $ grouptalk.add("동삼용|나 심개시간에 봤는데 맥락학습법인가 그런 게 있어서")
                # $ grouptalk.add("연속|공부할 때 술 마시면 시험칠 때도 술 마셔야 한다던데?")
                # $ grouptalk.add("해장중|?? 오 개이득?")
                # $ grouptalk.add("박대현|저 알콜 중독자 자식..")
                # $ grouptalk.add("유현재|미래야 우리는 쟤랑 같이 공부하지 말자..")
                # $ grouptalk.add("노미래|그래..좋은 생각이야..")
                # $ grouptalk.add("김진일|같이 듣는 수업 드랍하길 잘한거라고 봐야하나..")

            #elif day == 4 :
                # $ grouptalk.add("날짜|4월 19일 목요일")
                # $ grouptalk.add("해장중|결정했어!")
                # $ grouptalk.add("주인공|?? 뭐를??")
                # $ grouptalk.add("해장중|나는 딘 공부법을 하기로 결정했어!")
                # $ grouptalk.add("동삼용|딘 공부법?")
                # $ grouptalk.add("해장중|요즘 유행하는 공부법인데 시험 범위의 반의 반의 반만 공부하는 거임!!")
                # $ grouptalk.add("안금지|...그거 그러다 학점도 <D> 받는다는 소문이 있던데?")
                # $ grouptalk.add("해장중|....")
                # $ grouptalk.add("유현재|ㅉ...")
                # $ grouptalk.add("노미래|ㅉ....")
                # $ grouptalk.add("박대현|근데 진짜 시험기간이라 그런가 저런것만 봐도 재밌긴 하더랔ㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|사슴공부법인가 그런 것도 있던데")
                # $ grouptalk.add("김진일|엌ㅋㅋ 그거 나도 봄 뭐지 사슴은 사자에게 쫓길 때 집중력을 최고로 발휘한다고")
                # $ grouptalk.add("연속|시험 치기 하루전인가 몇 시간 전부터 공부한다는 거 아냐?? ㅋ")
                # $ grouptalk.add("박대현|ㅇㅇ 그겈ㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|진짜...우리나라의 드립력은...")

            #elif day == 5 :
                # $ grouptalk.add("날짜|4월 20일 금요일")
                # $ grouptalk.add("주인공|아니 뭐했다고 벌써 일주일이 다갔냐? 실화야 이거??")
                # $ grouptalk.add("주인공|시험 공부 진짜 거의 못했는데..")
                # $ grouptalk.add("안금지|나도..시험 범위 한 번도 못봤어..")
                # $ grouptalk.add("동삼용|?? 금지 너 도서관에 계속 박혀있는 거 본거 같은데?")
                # $ grouptalk.add("안금지|에이 잘못봤겠지...;;")
                # $ grouptalk.add("동삼용|? 그런가??")
                # $ grouptalk.add("해장중|이렇게 된 이상 뉴런 공부법으로 간다!")
                # $ grouptalk.add("박대현|그건 뭐임? 처음 들어보는데??")
                # $ grouptalk.add("해장중|자기 전까지 대충 보고, 자는 동안에 일어나는 뉴런끼리의 시냅스 결합을 믿는 것이지!!")
                # $ grouptalk.add("유현재|...결국 현실 도피랑 다를 바가 뭐냐")
                # $ grouptalk.add("노미래|다른 점이 없는 것 같은데?")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋ 그래도 딘 공부법에서 이 정도면 많이 발전한거 아니냐!")
                # $ grouptalk.add("김진일|그건 인정한다..")
                # $ grouptalk.add("동삼용|다들 파이팅.. 시험 기간 파이..팅..")

            #elif day == 6 :
                # $ grouptalk.add("날짜|4월 21일 토요일")
                # $ grouptalk.add("주인공|나는 아무 생각이 없다.")
                # $ grouptalk.add("주인공|왜냐하면 아무 생각이 없기 때문이다.")
                # $ grouptalk.add("해장중|나는 아무 것도 하고 싶지 않다.")
                # $ grouptalk.add("연속|지금도 아무 것도 하고 있지 않지만.")
                # $ grouptalk.add("연속|더 격렬하게 아무 것도 하고 싶지 않다.")
                # $ grouptalk.add("김진일|이틀 뒤부터 시험이라니..")
                # $ grouptalk.add("유현재|뭔가 수능 끝난 뒤로 공부하는 법 자체를 잊어버린 것 같은 느낌이야..")
                # $ grouptalk.add("노미래|내 말이..나 고등학교 때 어떻게 공부했지..")
                # $ grouptalk.add("주인공|내가 봤을 때 난 이 학교 전산오류전형으로 붙은게 틀림없어..")
                # $ grouptalk.add("해장중|나도...")
                # $ grouptalk.add("동삼용|전산오류전형이 뭐여??")
                # $ grouptalk.add("박대현|전산에 오류가 나서 붙지 말아야할 사람이 붙어버린거?")
                # $ grouptalk.add("동삼용|엌?? 뻔대 그랬어?? 실망임..")
                # $ grouptalk.add("주인공|...당연히 농담이지 이 친구야..")
                # $ grouptalk.add("주인공|진짜 그러면 너무 슬플 것 같다 ㅠㅜㅠㅜㅜ")
                # $ grouptalk.add("동삼용|아 농담이었어? ㅈㅅㅈㅅ;;")
                # $ grouptalk.add("주인공|괜찮...아..흑..")
                # $ grouptalk.add("해장중|우리 존재 파이팅...")

        elif week == 4 :
            if day == 0 :
                $ grouptalk.add("날짜|4월 22일 일요일")
                $ grouptalk.add("주인공|아... 내일부터 중간고사 시작이다 ㅠㅠㅠㅠㅠ")
                $ grouptalk.add("유현재|아아아아아 시험 빨리 끝났으면 좋겠다아아아")
                $ grouptalk.add("동삼용|시험 족보있어??")
                $ grouptalk.add("주인공|아니 없어 ㅠㅠㅠ")
                $ grouptalk.add("동삼용|으헉 ㅠㅠㅠ 난 내 시험 족보 왠만하면 다 구해서 그나마 괜찮은데...")
                $ grouptalk.add("주인공|부럽다 ㅠㅠㅠㅠ")
                $ grouptalk.add("김진일|아 시험 때려부수고 싶다...")
                $ grouptalk.add("노미래|진심... 아 그냥 하지말까")
                $ grouptalk.add("유현재|안돼 ㅋㅋㅋ 얼른 공부하자! 화이팅!")
                $ grouptalk.add("해장중|다른 과는 벌써 장터도 하던데 ㅠㅠㅠ 거긴 시험 끝나서 그런건가?")
                $ grouptalk.add("김진일|오 장터?? 내일 장터가서 술이나 ㄱㄱ?")
                $ grouptalk.add("오덕현|야레야레 와타시...내일 시험이 있달까..? ㅠㅠ")
                $ grouptalk.add("장중 |진일이 내일 ㄱㄱ?")
                $ grouptalk.add("박대현|난 모르겠다~ 내일 장터나 가자~")
                $ grouptalk.add("노미래|우리도 시험 끝나고 얼른 장터하자!!!")
                $ grouptalk.add("주인공|ㅋㅋㅋ 그러자")

            elif day == 1 :
                $ grouptalk.add("날짜|4월 23일 월요일")
                $ grouptalk.add("주인공|얘들아 어제 장터 얘기 나와서 그런데")
                $ grouptalk.add("주인공|장터준비위원회를 슬슬 정해야할 것 같아!!")
                $ grouptalk.add("주인공|우리장터 날짜는 5월 3일에 할것 같아!")
                $ grouptalk.add("해장중|오 좋아좋아!!!")
                $ grouptalk.add("연속|장터 가즈아~~~")
                $ grouptalk.add("동삼용|장준위 하면 뭐하는거야??")
                $ grouptalk.add("주인공|대충 생각해보면 포스터 만들고 메뉴 정하고 장보는 거 아닐까??")
                $ grouptalk.add("주인공|장은 전날인 5월 2일에 보면 될것 같아!")
                $ grouptalk.add("동삼용|아하 오키오키 그럼 나도 할래!!!")
                $ grouptalk.add("유현재|나도222")
                $ grouptalk.add("박대현|나도333333")
                $ grouptalk.add("노미래|난 시험 때문에 ㅠㅠㅠ 장터 당일에 열심히 도와줄게")
                $ grouptalk.add("김진일|사람 부족하면 나도 장준위 해드릴게")
                $ grouptalk.add("오덕현|크...모두..아름다운 토모다치들이군....")

            #elif day == 2 :
                # $ grouptalk.add("날짜|4월 24일 화요일")
                # $ grouptalk.add("안금지|얘들아 나 내일 시험인데 공부 하나도 안했어 ㅋㅋㅋ")
                # $ grouptalk.add("연속|시험 망했다~")
                # $ grouptalk.add("노미래|어떡해 ㅋㅋㅋ 얼른 해 금지야")
                # $ grouptalk.add("안금지|나 아까 피곤해서 잠깐 잤는데")
                # $ grouptalk.add("연속|5시간이나 잤어 ㅋㅋㅋ")
                # $ grouptalk.add("유현재|엌ㅋㅋㅋ 금지 시험 던지는건가?")
                # $ grouptalk.add("해장중|난 오늘 장터 갔다왔지롱~")
                # $ grouptalk.add("김진일|와 오늘 개많이 마셨다")
                # $ grouptalk.add("해장중|? 우리 1병도 안마셨잖아 ㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|술보다는 분위기에 취해버렸지...")
                # $ grouptalk.add("노미래|ㅋㅋㅋㅋ 뭐래 ㅋㅋㅋㅋ")
                # $ grouptalk.add("동삼용|아 중간고사 극혐이다아아아아...")

            #elif day == 3 :
                # $ grouptalk.add("날짜|4월 25일 수요일")
                # $ grouptalk.add("박대현|오늘 야식 드실분??")
                # $ grouptalk.add("유현재|나 내일 시험이라...ㅠㅠ")
                # $ grouptalk.add("노미래|나도 ㅠㅠㅠ")
                # $ grouptalk.add("동삼용|어떤거 먹을거야???")
                # $ grouptalk.add("김진일|야식이면 치킨???")
                # $ grouptalk.add("박대현|치킨 좋지")
                # $ grouptalk.add("동삼용|깐풍기 같은거 시키는거야??")
                # $ grouptalk.add("해장중|....??? 깐풍기?? ㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|깐풍기 뭐야 ㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("동삼용|엥...? 왜 ㅋㅋ")
                # $ grouptalk.add("노미래|갑분깐 ㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("박대현|ㅋㅋㅋㅋㅋ 아 ㄴㄴ 깐풍기말고 그냥 치킨!")
                # $ grouptalk.add("해장중|난 다음에 먹을게 ㅋㅋㅋㅋ 조만간 깐풍기도 ㄱㄱ")

            #elif day == 4 :
                # $ grouptalk.add("날짜|4월 26일 목요일")
                # $ grouptalk.add("안금지|똑똑 아무도 없나요?")
                # $ grouptalk.add("연속|나 오늘 하루종일 자서 내일 시험 공부 하나도 못했어 ㅋㅋ")
                # $ grouptalk.add("노미래|헐 어떡해 ㅠㅠㅠㅠ")
                # $ grouptalk.add("안금지|어쩔수 없지 ㅋㅋㅋ")
                # $ grouptalk.add("박대현|화이팅!!!")
                # $ grouptalk.add("해장중|내일 시험 많아서 애들 톡 안보는 듯 ㅠㅠ")

            #elif day == 5 :
                # $ grouptalk.add("날짜|4월 27일 금요일")
                # $ grouptalk.add("동삼용|나 중간고사 끝!!!!!!!!!!!!!!!!!!!")
                # $ grouptalk.add("해장중|개부럽다 ㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠㅠ")
                # $ grouptalk.add("김진일|삼용아 조용히 하자.")
                # $ grouptalk.add("동삼용|왜 ㅋㅋㅋㅋ 너 아직 남았어??")
                # $ grouptalk.add("김진일|다음주 시험 2개다")
                # $ grouptalk.add("동삼용|아...")
                # $ grouptalk.add("해장중|아.....")
                # $ grouptalk.add("노미래|으아...ㅠㅠㅠ 그래도 나도 다음주 월요일에 하나만 더 보면 끝!!!!")
                # $ grouptalk.add("연속|힘내자!!!")
                # $ grouptalk.add("유현재|으헉....ㅠㅠ")
                # $ grouptalk.add("안금지|하하 난 오늘도 망했다")

            elif day == 6 :
                $ grouptalk.add("날짜|4월 28일 토요일")
                $ grouptalk.add("주인공|나도 드디어 시험 끝났다아아아아!!!!ㅠㅠㅠㅠㅠ")
                $ grouptalk.add("해장중|수고했어 ㅋㅋㅋㅋ")
                $ grouptalk.add("김진일|와우~~ 오늘 술 ㄱㄱ?? ㅋㅋㅋ")
                $ grouptalk.add("해장중|헛.. 땡기는데.. 한잔 할까")
                $ grouptalk.add("유현재|ㅋㅋㅋㅋ 오늘도 술이냐")
                $ grouptalk.add("오덕현|오 사케 한 잔 할까..나....?")
                $ grouptalk.add("유현재|ㅋㅋㅋㅋㅋ 덕현이도 오늘 끼냐")
                $ grouptalk.add("오덕현|훗... 와타시모 사케를 스키(좋아)..랄까..?")
                $ grouptalk.add("김진일|덕현이 오늘 죽겠네 ㅋㅋ")
                $ grouptalk.add("해장중|뻔대도 ㄱㄱ?? 축하의 기념으로 ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("노미래|그만좀 마셔 너네들 ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("동삼용|술하면 고량주지~")
                $ grouptalk.add("연속|어디가서 마실거야?")
                $ grouptalk.add("오덕현|와타시다치노 <하-토>가 가리키는곳으로....훗")

    elif month == 5 :
        if week == 1 :
            #if day == 0 :
                # $ grouptalk.add("날짜|5월 1일 일요일")
                # $ grouptalk.add("해장중|이제 장터까지 이틀밖에 안남았다!!!")
                # $ grouptalk.add("박대현|!!!! 기대된다 ㅎㅎㅎㅎ")
                # $ grouptalk.add("유현재|돈 개많이 벌자 ㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("박대현|ㅇㅇㅇ ㅋㅋㅋㅋ 번 돈으로 뒷풀이 거하게 ㄱㄱ")
                # $ grouptalk.add("김진일|드디어 소주에서 벗어나는건가??? 양주 ㄱㄱ")
                # $ grouptalk.add("동삼용|고량주 ㄱㄱㄱㄱ")
                # $ grouptalk.add("해장중|오 양꼬치도 개맛있겠다")
                # $ grouptalk.add("노미래|기대된다 ㅋㅋㅋ 우리 많이 팔자 얘들아")
                # $ grouptalk.add("주인공|모두 다 화이팅!!")
                # $ grouptalk.add("김진일|내일 장보러 갈건데 장준위 아닌사람도 환영~")
                # $ grouptalk.add("해장중|많이 가줄수록 우리 뻔대가 더 열심히 일한대!! (소곤소곤)")
                # $ grouptalk.add("노미래|뻔대 그만 괴롭혀 ㅋㅋㅋㅋㅋ")

            if day == 1 :
                $ grouptalk.add("날짜|5월 2일 월요일")
                $ grouptalk.add("김진일|와 오늘 장 개많이 봤다")
                $ grouptalk.add("연속|어깨 뻐근하네")
                $ grouptalk.add("동삼용|진심...")
                $ grouptalk.add("김진일|이 형이 또 한 힘 써줬지 이말이야~")
                $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("노미래|으아아아 너무 힘들었다 ㅠㅠㅠ")
                $ grouptalk.add("박대현|수고했어 얘들아!!!!")
                $ grouptalk.add("해장중|진짜 수고수고~!")
                $ grouptalk.add("오덕현|민나 혼또니 수고...랄까?")
                $ grouptalk.add("유현재|ㅎㅎㅎㅎ 이제 내일 장터 당일만 남았다!")
                $ grouptalk.add("주인공|너무 수고했다 얘들아 ㅎㅎㅎ 하루만 더 고생하자 ㅠㅠㅠ")

            #elif day == 3 :
                # $ grouptalk.add("날짜|5월 4일 수요일")
                # $ grouptalk.add("해장중|장.터.끝.났.다......!")
                # $ grouptalk.add("유현재|힘들었다....")
                # $ grouptalk.add("김진일|우리 돈 얼마 범?")
                # $ grouptalk.add("해장중|몰겠 ㅋㅋㅋㅋ 나중에 세봐야겠다")
                # $ grouptalk.add("동삼용|어제 뒷풀이로 얼마 썼지")
                # $ grouptalk.add("연속|술 엄청 많이 마신것 같은데")
                # $ grouptalk.add("박대현|ㅋㅋㅋㅋ 다 쓴거 아니야??")
                # $ grouptalk.add("동삼용|에이 설마....ㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|어젯밤 불태우긴 했다 ㅋㅋㅋㅋ")
                # $ grouptalk.add("노미래|진짜 수고했어 얘들아!!!!")
                # $ grouptalk.add("오덕현|오츠카레...")
                # $ grouptalk.add("동삼용|덕현아 그건 무슨말이야??")
                # $ grouptalk.add("오덕현|야레야레....")
                # $ grouptalk.add("동삼용|????")
                # $ grouptalk.add("김진일|덕현아 좋은말로 할때 제대로 말하자")

            #elif day == 4 :
                # $ grouptalk.add("날짜|5월 5일 목요일")
                # $ grouptalk.add("김진일|ㄱ?")
                # $ grouptalk.add("해장중|ㄱ?")
                # $ grouptalk.add("유현재|ㄱ?")
                # $ grouptalk.add("박대현|ㄱ?")
                # $ grouptalk.add("동삼용|뭐가 ㄱ? 이야???")
                # $ grouptalk.add("노미래|또 술이냐 ㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|바로 맞췄네 ㅋㅋㅋ")
                # $ grouptalk.add("연속|진짜 술마실분???")
                # $ grouptalk.add("동삼용|에휴... 장터 끝난지가 언제라고..")
                # $ grouptalk.add("연속|벌써 또 마시냐")
                # $ grouptalk.add("주인공|난 아직도 해장이 안된듯 ㅠㅠ")
                # $ grouptalk.add("김진일|원래 술은 술로 해장하는 것이다!")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋ ㄱㄱ")
                # $ grouptalk.add("유현재|오늘만 산다..!")
                # $ grouptalk.add("오덕현|...!")
                # $ grouptalk.add("노미래|현재야....")
                # $ grouptalk.add("해장중|진짜 술 드실분??")
                # $ grouptalk.add("김진일|너 가면 나 감")
                # $ grouptalk.add("해장중|나도 ㅋㅋ")

            #elif day == 5 :
                # $ grouptalk.add("날짜|5월 6일 금요일")
                # $ grouptalk.add("유현재|불...금!")
                # $ grouptalk.add("해장중|불...금!")
                # $ grouptalk.add("김진일|ㄱ?")
                # $ grouptalk.add("주인공|ㅋㅋㅋㅋㅋ 어제 마시지 않았어??")
                # $ grouptalk.add("김진일|결국 아무말도 없어서 흐지부지 됨 ㅋㅋ")
                # $ grouptalk.add("해장중|ㅋㅋ")
                # $ grouptalk.add("노미래|으이구 그럴 줄 알았다 ㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("유현재|불금 다들 어떻게 보내시나요!!!")
                # $ grouptalk.add("안금지|난 과제...ㅠㅠ")
                # $ grouptalk.add("오덕현|와타시는 집에서 애니 정주행 ㅎㅎ")
                # $ grouptalk.add("김진일|오 어떤거?")
                # $ grouptalk.add("오덕현|진일쿤도 애니 보는 건가요...!!!")
                # $ grouptalk.add("김진일|ㄴ 걍 물어봄 ㅋ")
                # $ grouptalk.add("연속|사실 말해도 모를듯")

            #elif day == 6 :
                # $ grouptalk.add("날짜|5월 7일 토요일")
                # $ grouptalk.add("동삼용|다들 머함~")
                # $ grouptalk.add("해장중|잠")
                # $ grouptalk.add("동삼용|그럼 카톡 어떻게 해 ㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|쿨~")
                # $ grouptalk.add("김진일|ㅋㅋ 귀엽네")
                # $ grouptalk.add("오덕현|...?!")
                # $ grouptalk.add("김진일|덕현아 이상한거 하지마라")
                # $ grouptalk.add("유현재|으아아아 과제하기 귀찮다아아아")
                # $ grouptalk.add("연속|시험 끝나고 쉴시간을 안주네")
                # $ grouptalk.add("박대현|롤 ㄱ?")
                # $ grouptalk.add("유현재|아 진심 때려치고 겜이나 한판 할까")
                # $ grouptalk.add("박대현|ㄱㄱ")
                # $ grouptalk.add("노미래|ㅡㅡ  과제 해")
                # $ grouptalk.add("유현재|알았어 미래야 ㅠㅠ")
                # $ grouptalk.add("박대현|ㅠㅠ")

        elif week == 2 :
            #if day == 0 :
                # $ grouptalk.add("날짜|5월 8일 일요일")
                # $ grouptalk.add("주인공|뭐했다고 내일 월요일이냐")
                # $ grouptalk.add("해장중|오우 슅.......")
                # $ grouptalk.add("노미래|그러게 ㅠㅠㅠㅠ 으아아아아")
                # $ grouptalk.add("연속|아직 5월이지만")
                # $ grouptalk.add("연속|종강했으면 좋겠다.....")
                # $ grouptalk.add("김진일|아 내일 휴강 안하나")
                # $ grouptalk.add("동삼용|ㅋㅋㅋ 왜~")
                # $ grouptalk.add("연속|그래도 학교오면 친구들 보고 좋지")
                # $ grouptalk.add("연속|안그렇냐 친구들아!")
                # $ grouptalk.add("오덕현|오마에...(코쓱)")
                # $ grouptalk.add("연속|그래.. 벌써 그렇게 됐군")
                # $ grouptalk.add("연속|와타시의 토모다치라...")
                # $ grouptalk.add("연속|이거이거 영광으로 알라고옷")
                # $ grouptalk.add("김진일|덕현아 경고했다")
                # $ grouptalk.add("유현재|아 학교가기 싫다ㅏㅏㅏㅏㅏㅏㅏㅏㅏㅏ")

            if day == 1 :
                $ grouptalk.add("날짜|5월 9일 월요일")
                $ grouptalk.add("유현재|개이득~~~ 내일 휴강한다고 문자옴~~~")
                $ grouptalk.add("김진일|와 진심 부럽다")
                $ grouptalk.add("해장중|진심??? 아 개부럽다")
                $ grouptalk.add("유현재|어디 놀러갈까 내일 수업 그거 하난데")
                $ grouptalk.add("노미래|오!!!! 그럴까?? 우리 놀러 가자!!")
                $ grouptalk.add("김진일|둘이 재~~~밌게 노세요~")
                $ grouptalk.add("해장중|ㅋ")
                $ grouptalk.add("동삼용|오오 재밌겠다 내일 같이 놀자!!!")
                $ grouptalk.add("박대현|눈치있게 빠져주자 삼용아")
                $ grouptalk.add("노미래|왜그래 얘들아 ㅋㅋㅋㅋ")
                $ grouptalk.add("유현재|아니야 다같이 놀자 ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|만약 데이트 할거 였으면")
                $ grouptalk.add("연속|애초에 여기다 말도 안했겠지~")
                $ grouptalk.add("노미래|♥")
                $ grouptalk.add("김진일|하....")
                $ grouptalk.add("오덕현|크...칙쇼...!")

            #elif day == 2 :
                # $ grouptalk.add("날짜|5월 10일 화요일")
                # $ grouptalk.add("해장중|오늘 한강뻔모 개잼~")
                # $ grouptalk.add("연속|드디어 학교 밖에 나와서 놀았네")
                # $ grouptalk.add("김진일|ㅋㅋㅋ 생각해보니까 그렇네")
                # $ grouptalk.add("연속|와 5월이나 돼서야 나가서 놀았네")
                # $ grouptalk.add("오덕현|아쉽군....")
                # $ grouptalk.add("동삼용|덕현이 왜 못왔어 ㅠㅠㅠ")
                # $ grouptalk.add("오덕현|내 방 앞에 결계가 쳐있었다...라고나 할까요?")
                # $ grouptalk.add("연속|칫...")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ 뭐냐 그건")
                # $ grouptalk.add("김진일|결계 깨러 간다")
                # $ grouptalk.add("연속|덕현아 너도 부숴질 준비해라")

            elif day == 3 :
                $ grouptalk.add("날짜|5월 11일 수요일")
                $ grouptalk.add("주인공|얘들아 다른 반 한테 연락왔는데")
                $ grouptalk.add("연속|같이 운동회 하는거 어떄??")
                $ grouptalk.add("김진일|오 이거 좋다")
                $ grouptalk.add("해장중|운동회?")
                $ grouptalk.add("연속|뭐하는건데 ㅋㅋ")
                $ grouptalk.add("오덕현|손나 바카나!")
                $ grouptalk.add("연속|운동회라면")
                $ grouptalk.add("연속|애니에서 나오는 청춘 가득한 이벤트...!?!?")
                $ grouptalk.add("김진일|아니 그런거 아니야 덕현아")
                $ grouptalk.add("연속|가만히 있어")
                $ grouptalk.add("오덕현|칙쇼")
                $ grouptalk.add("해장중|아 빨리 ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("유현재|그냥 축구나 달리기 이런 종목 정해서")
                $ grouptalk.add("연속|다른 반이랑 대결하는 거 아니야??")
                $ grouptalk.add("주인공|ㅇㅇ 맞아 ㅋㅋㅋ 다른 반이 같이 하자해서")
                $ grouptalk.add("연속|너네들 한테 물어보고 결정한다했어")
                $ grouptalk.add("유현재|난 좋아!")
                $ grouptalk.add("김진일|콜")
                $ grouptalk.add("박대현|오오 운동회 좋다 나 참!")
                $ grouptalk.add("동삼용|무술 같은건 없어??")
                $ grouptalk.add("김진일|있겠냐 삼용아 ㅉㅉ")

            elif day == 4 :
                $ grouptalk.add("날짜|5월 12일 목요일")
                $ grouptalk.add("주인공|운동회 투표!!!!")
                $ grouptalk.add("연속|투표 열었으니깐 얼른 해주세요~")
                $ grouptalk.add("유현재|ㄱㄱ")
                $ grouptalk.add("박대현|ㄱㄱ")
                $ grouptalk.add("김진일|가즈아~")

            #elif day == 5 :
                # $ grouptalk.add("날짜|5월 13일 금요일")
                # $ grouptalk.add("안금지|나 과제 해야하는데 오늘 또 자버렸어 ㅠㅠ")
                # $ grouptalk.add("연속|어떡하지?")
                # $ grouptalk.add("노미래|ㅠㅠㅠㅠ")
                # $ grouptalk.add("김진일|지금부터라도 해")
                # $ grouptalk.add("유현재|금지 또 잠? ㅋㅋㅋㅋ")
                # $ grouptalk.add("안금지|망했어 ㅎㅎㅎ")
                # $ grouptalk.add("동삼용|슬슬 과제가 많아진다")
                # $ grouptalk.add("박대현|아 교수님들은 우리를 왜 가만히 못놔둘까")
                # $ grouptalk.add("유현재|진심...")

            #elif day == 6 :
                # $ grouptalk.add("날짜|5월 14일 토요일")
                # $ grouptalk.add("해장중|오랜만에 술 마실 분??")
                # $ grouptalk.add("연속|모처럼 주말인데 달려야지")
                # $ grouptalk.add("김진일|우리 안마신지 거의 일주일 되지않음?")
                # $ grouptalk.add("유현재|오늘은 나도 땡긴다 ㄱㄱ")
                # $ grouptalk.add("연속|미래도 갈래??")
                # $ grouptalk.add("노미래|나 과제 ㅠㅠㅠㅠ ")
                # $ grouptalk.add("오덕현|와타시모 오-사케를 마시러 가볼까나..?")
                # $ grouptalk.add("김진일|우리 사케 안마시고 소주 마실거임")
                # $ grouptalk.add("오덕현|큿...할 수 없지..")
                # $ grouptalk.add("연속|오늘은 소주인가...후훗")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("동삼용|나도 가고싶다 ㅠㅠㅠㅠ")
                # $ grouptalk.add("유현재|삼용쓰 마시자~~~")
                # $ grouptalk.add("동삼용|나도 오늘 과제 ㅠㅠㅠ")
                # $ grouptalk.add("해장중|대충하고 ㄱㄱ")
                # $ grouptalk.add("주인공|ㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|술도 좋지만")
                # $ grouptalk.add("주인공|다들 운동회 투표하는거 잊지말고~")

        elif week == 3 :
            if day == 0 :
                $ grouptalk.add("날짜|5월 15일 일요일")
                # 운동회 참불 투표 진행
                $ grouptalk.add("주인공|얘들아 ㅋㅋㅋㅋ")
                $ grouptalk.add("주인공|운동회 참불 투표좀 ㅠㅠ 아직 20명이나 안했어")
                $ grouptalk.add("안금지|얘들아 나도 부탁좀 ㅠㅠ")
                $ grouptalk.add("연속|이번 과제가 설문 해야되서")
                $ grouptalk.add("연속|이 링크에서 설문 좀 해주라ㅋㅋㅋㅋ")
                $ grouptalk.add("유현재|나도 글기 과제 설문좀 ㅠㅠㅠ")
                $ grouptalk.add("김진일|다 자기 하고 싶은 말 하는건가 ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("주인공|얘들아 투표 꼭 좀 부탁해 ㅠㅠ")
                # 운동회 참불 투표 강제종료
                $ grouptalk.add("주인공|얘들아")
                $ grouptalk.add("연속|우리 뒷풀이는 어디서 할까?")
                $ grouptalk.add("해장중|매번 하던 거기?")
                $ grouptalk.add("김진일|바로 그 곳??")
                $ grouptalk.add("연속|레알 참트루???")
                $ grouptalk.add("주인공|거기가 어딘데???")
                $ grouptalk.add("해장중|너네집ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|뻔대텔에서 자고 가야겠다")
                $ grouptalk.add("박대현|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("오덕현|오옷...! 와타시모 가겠다는...!!")

            #elif day == 1 :
                # $ grouptalk.add("날짜|5월 16일 월요일")
                # $ grouptalk.add("해장중|김진일 좋니 들어본사람??")
                # $ grouptalk.add("박대현|오오 잘해???")
                # $ grouptalk.add("용삼|거의 박효신")
                # $ grouptalk.add("박대현|진짜??ㅋㅋㅋ 대박")
                # $ grouptalk.add("용삼|박효신 나이랑 점수가 비슷")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|야 이 노양심들아")
                # $ grouptalk.add("연속|공짜로 노래 불렀으면")
                # $ grouptalk.add("연속|비밀은 지켜줘야지 ㅅㅂ")
                # $ grouptalk.add("노미래|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|웃기냐?")
                # $ grouptalk.add("노미래|응 웃긴데????")
                # $ grouptalk.add("김진일|하... 진짜 화나게하네 얘들이")
                # $ grouptalk.add("연속|갠톡하자")

            #elif day == 2 :
                # $ grouptalk.add("날짜|5월 17일 화요일")
                # $ grouptalk.add("주인공|투표 마감까지 하루!")
                # # 운동회 참불 투표 진행
                # $ grouptalk.add("안금지|얘들아")
                # $ grouptalk.add("연속|ㅠㅠㅠ")
                # $ grouptalk.add("연속|나도 이번주까진데")
                # $ grouptalk.add("연속|꼭 설문 좀 해줘 ㅠㅠㅠ")
                # $ grouptalk.add("주인공|금지야.... 제발")
                # $ grouptalk.add("주인공|그래도 과 행산데")
                # $ grouptalk.add("주인공|공지 안 묻히게 좀 해줘...")
                # $ grouptalk.add("김진일|우리 이번에 종목은 뭐하지?")
                # $ grouptalk.add("주인공|투표 끝나고")
                # $ grouptalk.add("주인공|준비위원회에서 정할거야")
                # $ grouptalk.add("주인공|진일아 과잠준비때처럼 부탁해 ㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|음....")
                # $ grouptalk.add("연속|나 요즘 좀 바쁜데;;;;")
                # $ grouptalk.add("주인공|말 나온김에!!")
                # $ grouptalk.add("주인공|운동회 준비위원 모집해요!!")
                # # 운동회 참불 투표 강제 종료
                # $ grouptalk.add("주인공|우리 운동회")
                # $ grouptalk.add("주인공|종목이랑 뒷풀이 이런거 정해야 되는데")
                # $ grouptalk.add("주인공|나 혼자는 힘들어서")
                # $ grouptalk.add("주인공|과잠 맞출때처럼 준비위원회 만들려고 해!!")
                # $ grouptalk.add("주인공|많이많이 지원해주세요~")
                # $ grouptalk.add("주인공|지원하시면")
                # $ grouptalk.add("주인공|종목도 정하고, 뒷풀이 장소도 정하고")
                # $ grouptalk.add("주인공|무엇보다!!!")
                # $ grouptalk.add("주인공|저랑 친해질 수 있는 절호의 찬스~")
                # $ grouptalk.add("노미래|누가 너랑 친해지려고 그걸하냨ㅋㅋㅋㅋ")
                # $ grouptalk.add("유현재|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|팩트로 조지네")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|에이 회의하고")
                # $ grouptalk.add("주인공|나랑 야식 먹고 너무 좋다...")
                # $ grouptalk.add("유현재|너랑 먹느니")
                # $ grouptalk.add("연속|덕현 짱이랑 애니메이션 보겠다는!!!")
                # $ grouptalk.add("김진일|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")

            #elif day == 3 :
                # $ grouptalk.add("날짜|5월 18일 수요일")
                # $ grouptalk.add("주인공|내일부터")
                # $ grouptalk.add("주인공|운동회 준비 위원회 회의합니다!!!")
                # $ grouptalk.add("주인공|아직까지 지원가능하니까")
                # $ grouptalk.add("주인공|많이 지원해주세요 ㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|ㅋㅋㅋ 복싱하자 복싱")
                # $ grouptalk.add("연속|내가 우승시켜줄게")
                # $ grouptalk.add("노미래|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("동삼용|탁구하자 탁구 ㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|나 길림성에서 이름 좀 날림 ㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|위원회 들어오면 정할 수 있어!!")
                # $ grouptalk.add("동삼용|그건 좀 ㅜㅜ 내가 바빠서..")
                # $ grouptalk.add("연속|여튼 탁구 하면")
                # $ grouptalk.add("연속|우리 과 우승시켜 줄게 ㅋㅋㅋ")

            #elif day == 4 :
                # $ grouptalk.add("날짜|5월 19일 목요일")
                # $ grouptalk.add("주인공|핵꿀잼 운동회 준비중 ㅋㅋㅋ")
                # $ grouptalk.add("주인공|진짜 안오면 후회한다 ㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|준비위원회가 열일하고 있습니다!")
                # $ grouptalk.add("해장중|하 진짜 이번에도 준비위하네")
                # $ grouptalk.add("연속|ㅋㅋㅋ 뻔대는 진짜")
                # $ grouptalk.add("연속|나 없으면 일 어떻게 하냐")
                # $ grouptalk.add("김진일|과잠때도")
                # $ grouptalk.add("연속|내가 주도해서 일했잖아 ㅋㅋㅋ")
                # $ grouptalk.add("동삼용|그래서")
                # $ grouptalk.add("연속|아무도 안입잖아")
                # $ grouptalk.add("유현재|ㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("오덕현|그걸 입는다는 건...")
                # $ grouptalk.add("연속|오마에.. <혼모노> 로군...후훗")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")

            #elif day == 5 :
                # $ grouptalk.add("날짜|5월 20일 금요일")
                # $ grouptalk.add("해장중|내일")
                # $ grouptalk.add("연속|다 뒤풀이 오실???")
                # $ grouptalk.add("오덕현|와타시는 미코짱 직거래로 못갈 것 같소..")
                # $ grouptalk.add("김진일|ㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|내일 술 마시자 술술")
                # $ grouptalk.add("연속|우리 과의 위엄을 보여주자")
                # $ grouptalk.add("주인공|진일이 내일 병샷 ㄱ?")
                # $ grouptalk.add("김진일|기본이지")
                # $ grouptalk.add("연속|의리주 가자")
                # $ grouptalk.add("해장중|제일 먼저 도망갈 놈이 ㅋㅋㅋ")
                # $ grouptalk.add("유현재|ㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|내일 다이다이 뜨자")
                # $ grouptalk.add("해장중|덤벼라 ㅋㅋㅋ")

            elif day == 6 :
                $ grouptalk.add("날짜|5월 21일 토요일")
                $ grouptalk.add("해장중|아 운동회 개힘들었다")
                $ grouptalk.add("유현재|지금은 뭐해 ㅋㅋㅋ")
                $ grouptalk.add("해장중|뒷풀이 ㅋㅋㅋ")
                $ grouptalk.add("유현재|술 많이 마심???")
                $ grouptalk.add("안금지|나도 갈걸 그랬다")
                $ grouptalk.add("유현재|장중이 신났겠네")
                $ grouptalk.add("김진일|다른 과 애들 술 못먹네 ㅋㅋㅋ")
                $ grouptalk.add("연속|의리주 지렸다 ㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|뻔대가 마지막 순서라서 ㅋㅋㅋㅋ")
                $ grouptalk.add("연속|거의 1병 한 번에 마신 것 같은데")
                $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|얘 쓰러짐 ㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|아 또 어떻게 집에 데려가냐")

        elif week == 4 :
            if day == 0 :
                $ grouptalk.add("날짜|5월 22일 일요일")
                $ grouptalk.add("주인공|진짜 어제 의리주 한 놈들")
                $ grouptalk.add("주인공|다 자수해라")
                $ grouptalk.add("주인공|특히 나한테 1병 넘게 남긴 놈들")
                $ grouptalk.add("김진일|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|마시고 제일 좋아하던 놈이")
                $ grouptalk.add("해장중|뻔대면")
                $ grouptalk.add("연속|병샷은 기본")
                $ grouptalk.add("연속|진짜 너 집 끌고가는데")
                $ grouptalk.add("연속|개 무거워서 빡침 ㅋㅋㅋ")

            elif day == 1 :
                $ grouptalk.add("날짜|5월 23일 월요일")
                $ grouptalk.add("김진일|뻔대야")
                $ grouptalk.add("연속|다음주에 공연하냐 ㅋㅋㅋ")
                $ grouptalk.add("동삼용|이제 과 생활 ㅂㅂ?")
                $ grouptalk.add("노미래|헐")
                $ grouptalk.add("연속|너무하다 뻔대야")
                $ grouptalk.add("주인공|모함 실화냐...")
                $ grouptalk.add("주인공|내가 일 얼마나 열심히 했는데ㅠ")
                $ grouptalk.add("김진일|라고 동아리로 떠난 뻔대가 말했습니다")

            #elif day == 2 :
                # $ grouptalk.add("날짜|5월 24일 화요일")
                # $ grouptalk.add("김진일|밥 먹을 사람?")
                # $ grouptalk.add("유현재|너?")
                # $ grouptalk.add("노미래|그리고 너")
                # $ grouptalk.add("유현재|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("김진일|없으면 형님들이랑 먹음 ㅂㅂ")

            elif day == 3 :
                $ grouptalk.add("날짜|5월 25일 수요일")
                $ grouptalk.add("유현재|내일 술 마실 사람??")
                $ grouptalk.add("연속|아 잘못침")
                $ grouptalk.add("연속|여기 아니였어 ㅋㅋㅋ")

            #elif day == 4 :
                # $ grouptalk.add("날짜|5월 26일 목요일")
                # $ grouptalk.add("주인공|애들아 나 다음주에 공연해 ㅋㅋㅋ")
                # $ grouptalk.add("주인공|많이 와주세요")
                # $ grouptalk.add("유현재|이제 뻔대 임기 끝났냐")
                # $ grouptalk.add("연속|동아리로 전념?")
                # $ grouptalk.add("오덕현|덕현쿤...은..속.상 하다고!")
                # $ grouptalk.add("노미래|ㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|가면 밥 사줌??")
                # $ grouptalk.add("연속|그러면 생각해 봄")
                # $ grouptalk.add("주인공|현재랑 많이~ 드세요~")

            #elif day == 5 :
                # $ grouptalk.add("날짜|5월 27일 금요일")
                # $ grouptalk.add("해장중|술 땡긴다")
                # $ grouptalk.add("연속|진일이 뭐함")
                # $ grouptalk.add("김진일|ㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|갠톡해")

            #elif day == 6 :
                # $ grouptalk.add("날짜|5월 28일 토요일")
                # $ grouptalk.add("해장중|뻔대야")
                # $ grouptalk.add("연속|우리 뻔모 안함?")
                # $ grouptalk.add("연속|곧 기말인데")
                # $ grouptalk.add("안금지|맞아맞아")
                # $ grouptalk.add("오덕현|와타시는 비-루를 간빠이 하고 싶다..랄까?")
                # $ grouptalk.add("김진일|뻔대 동아리에 정신팔림")
                # $ grouptalk.add("연속|우리끼리 ㄱㄱ?")
                # $ grouptalk.add("주인공|너네 너무하다 ㅠㅠㅠ")
                # $ grouptalk.add("연속|딱 1주만 하면 되는데")
                # $ grouptalk.add("안금지|에이 학기 중에도 가놓고?")

    elif month == 6 :
        if week == 1 :
            if day == 0 :
                $ grouptalk.add("날짜|6월 1일 일요일")
                $ grouptalk.add("해장중|오늘 뻔모 ㄱㄱ?")
                $ grouptalk.add("연속|곧 기말인데 한 번 모이자 ㅋㅋㅋ")
                $ grouptalk.add("김진일|오 ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|좋지")
                $ grouptalk.add("유현재|뻔대 없으니까")
                $ grouptalk.add("연속|장중이가 열일하네 ㅋㅋㅋ")
                $ grouptalk.add("연속|다음 학기 뻔대 ㄱ?")
                $ grouptalk.add("해장중|에바지....")
                $ grouptalk.add("연속|오늘 6시에 동학 ㄱㄱㄱ?")
                $ grouptalk.add("박대현|개굿개굿")

            #elif day == 1 :
                # $ grouptalk.add("날짜|6월 2일 월요일")
                # $ grouptalk.add("김진일|오늘 수업 간 사람 있냐....")
                # $ grouptalk.add("안금지|너네 글기 아무도 안왔더라 ㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|소주 40병 실화냐......")
                # $ grouptalk.add("연속|숙취 개쩔어")
                # $ grouptalk.add("유현재|아직까지")
                # $ grouptalk.add("연속|방에 누워있음")
                # $ grouptalk.add("연속|술병났다 ㅅㅂ")
                # $ grouptalk.add("김진일|와 나도 처음으로 숙취생김")
                # $ grouptalk.add("연속|그래도 개꿀잼이었다")
                # $ grouptalk.add("해장중|이따 같이 해장하실??")
                # $ grouptalk.add("김진일|ㅇㅋㅇㅋ")

            elif day == 2 :
                $ grouptalk.add("날짜|6월 3일 화요일")
                $ grouptalk.add("동삼용|금요일에")
                $ grouptalk.add("연속|뻔대 공연하던데")
                $ grouptalk.add("연속|가실 분???")

            elif day == 4 :
                $ grouptalk.add("날짜|6월 5일 목요일")
                $ grouptalk.add("동삼용|진짜 갈 사람 없음??")
                $ grouptalk.add("노미래|다음 주 기말ㅠㅠ")
                $ grouptalk.add("유현재|나도 트리플....")
                $ grouptalk.add("연속|맨날 밤샌다ㅠㅠㅠ")

            elif day == 5 :
                $ grouptalk.add("날짜|6월 6일 금요일")
                $ grouptalk.add("주인공|애들아 나 이따 저녁에 공연해")
                $ grouptalk.add("주인공|7시에 낙대 사운드 마인드 ㅋㅋㅋ")
                $ grouptalk.add("주인공|많이 와줘 ㅋㅋㅋ")
                $ grouptalk.add("박대현|파이팅!!!")
                $ grouptalk.add("오덕현|뻔대쿤 화이또!!")

            elif day == 6 :
                $ grouptalk.add("날짜|6월 7일 토요일")
                $ grouptalk.add("동삼용|어제 공연 고생했어 ㅋㅋㅋ")
                $ grouptalk.add("연속|멋있더라 ㅋㅋㅋㅋ")
                $ grouptalk.add("박대현|ㅅㄳㄱ")
                $ grouptalk.add("유현재|굿")

        elif week == 2 :
            #if day == 0 :
                # $ grouptalk.add("날짜|6월 8일 일요일")
                # $ grouptalk.add("박대현|오늘 공부하실 분 ㅋㅋㅋ")
                # $ grouptalk.add("연속|이번에도 망할삘이다 ㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|와... 이틀 후에 시험인데")
                # $ grouptalk.add("연속|공부 하나도 안하고")
                # $ grouptalk.add("연속|유튜브만 4시간째 보는중")
                # $ grouptalk.add("안금지|난 지금 6시간동안 핸드폰만 하고있어 ㅋㅋ")
                # $ grouptalk.add("연속|내일 시험 망했다 ㅎㅎ")
                # $ grouptalk.add("김진일|@해장중 너는 나냨ㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("해장중|ㄴㄴㄴ")
                # $ grouptalk.add("연속|너같은 한심한 애 아님")
                # $ grouptalk.add("김진일|ㅡㅡ")
                # $ grouptalk.add("해장중|같이 공부하자 진일아")
                # $ grouptalk.add("김진일|어디서")
                # $ grouptalk.add("해장중|중도?")
                # $ grouptalk.add("김진일|나 출발한다")
                # $ grouptalk.add("해장중|ㅇㅋ 나도 감")

            if day == 2 :
                $ grouptalk.add("날짜|6월 10일 화요일")
                $ grouptalk.add("안금지|애들아")
                $ grouptalk.add("연속|나 시험 망했어 ㅠㅠㅠ")
                $ grouptalk.add("유현재|징징 ㄴㄴㄴ")
                $ grouptalk.add("동삼용|진짜....")
                $ grouptalk.add("연속|저러고 중간고사도 1등 해놓고")

            #elif day == 3 :
                # $ grouptalk.add("날짜|6월 11일 수요일")
                # $ grouptalk.add("동삼용|이따 도라지에서 야식 드실 분?")
                # $ grouptalk.add("연속|파닭 ㄱㄱㄱ")
                # $ grouptalk.add("해장중|몇 시?")
                # $ grouptalk.add("동삼용|10시??")
                # $ grouptalk.add("박대현|나도 ㄱㄱㄱ")

            #elif day == 4 :
                # $ grouptalk.add("날짜|6월 12일 목요일")
                # $ grouptalk.add("해장중|이제 시험 두개 남았다....")
                # $ grouptalk.add("김진일|잘 봄?")
                # $ grouptalk.add("해장중|너보단?")
                # $ grouptalk.add("진일 |ㅡㅡ")
                # $ grouptalk.add("연속|내기 하실??")
                # $ grouptalk.add("해장중|아니")
                # $ grouptalk.add("노미래|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")

            #elif day == 6 :
                # $ grouptalk.add("날짜|6월 14일 토요일")
                # $ grouptalk.add("유현재|다들 시험 언제 끝나냐 ㅋㅋㅋ")
                # $ grouptalk.add("오덕현|나그스토 위이꾸?")
                # $ grouptalk.add("노미래|시험 기간 너무 길다...ㅠ")
                # $ grouptalk.add("김진일|덕현이 넌 진짜 뭐라는거냐")

        elif week == 3 :
            #if day == 0 :
                # $ grouptalk.add("날짜|6월 15일 일요일")
                # $ grouptalk.add("해장중|너네는")
                # $ grouptalk.add("연속|시험끝나면 뭐할거냐")
                # $ grouptalk.add("동삼용|집 가고 싶다")
                # $ grouptalk.add("해장중|오... 방학때 삼용이 집 투어?")
                # $ grouptalk.add("동삼용|오는게 너네야?")
                # $ grouptalk.add("연속|싫은데")
                # $ grouptalk.add("유현재|나도 갈래")
                # $ grouptalk.add("노미래|나도 갈래")
                # $ grouptalk.add("김진일|나도 갈래")
                # $ grouptalk.add("동삼용|진짜 올거야?ㅋㅋㅋㅋ")
                # $ grouptalk.add("연속|컴컴")
                # $ grouptalk.add("해장중|삼용이")
                # $ grouptalk.add("연속|술마실때 맨날")
                # $ grouptalk.add("연속|동네에서 자기 이름 대면 할인된다고 한거")
                # $ grouptalk.add("연속|검증한다")
                # $ grouptalk.add("동삼용|ㅋㅋㅋ 자신있다")
                # $ grouptalk.add("연속|나 길림성 지주야 ㅋㅋㅋㅋ")

            #elif day == 1 :
                # $ grouptalk.add("날짜|6월 16일 월요일")
                # $ grouptalk.add("안금지|ㅠㅠㅠㅠ")
                # $ grouptalk.add("연속|얘들아 나 시험 망했어")
                # $ grouptalk.add("김진일|안 궁금해 금지야")

            if day == 2 :
                $ grouptalk.add("날짜|6월 17일 화요일")
                $ grouptalk.add("해장중|경원 난이도 실화냐...")
                $ grouptalk.add("박대현|장중이 금메달 ㅋㅋㅋㅋㅋ")
                $ grouptalk.add("김진일|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("해장중|ㅠㅠㅠㅠ")
                $ grouptalk.add("연속|너는 잘봤냐 ㅋㅋㅋ")
                $ grouptalk.add("김진일|보긴 봤지")
                $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("연속|하... 학기 끝나면 군대가야겠다")
                $ grouptalk.add("연속|인생 답 없네...ㅠㅠ")

            elif day == 3 :
                $ grouptalk.add("날짜|6월 18일 수요일")
                $ grouptalk.add("주인공|얘들아")
                $ grouptalk.add("주인공|너네는 시험 언제 끝나?")
                $ grouptalk.add("주인공|언제끝나냐 ㅠㅠ")

            elif day == 4 :
                $ grouptalk.add("날짜|6월 19일 목요일")
                $ grouptalk.add("안금지|나 시험 끝났어!!!!")
                $ grouptalk.add("오덕현|오이오이...")
                $ grouptalk.add("박대현|52 극혐...")
                $ grouptalk.add("오덕현|그런건 오마에만 알고 있으라고!")
                $ grouptalk.add("김진일|요즘 오덕체 떡상중이네")
                $ grouptalk.add("연속|인터넷에서 개많이 쓰던데 ㅋㅋㅋㅋ")
                $ grouptalk.add("오덕현|..그..치만 진일짱....")
                $ grouptalk.add("연속|이렇게라도 하지 않으면")
                $ grouptalk.add("연속|진일짱이 나를 봐주질 않는걸...")
                $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("유현재|개웃ㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("노미래|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                $ grouptalk.add("주인공|우리 내일 종판건 기억하지???")
                $ grouptalk.add("주인공|가서 술마시자 ㅋㅋㅋㅋ")
                $ grouptalk.add("동삼용|나 중국 갈 수도 ㅠㅠ")
                $ grouptalk.add("김진일|가면 뻔대 또 의리주하냐 ㅋㅋㅋ")

            #elif day == 5 :
                # $ grouptalk.add("날짜|6월 19일 목요일")
                # $ grouptalk.add("안금지|나 시험 끝났어!!!!")
                # $ grouptalk.add("오덕현|오이오이...")
                # $ grouptalk.add("박대현|52 극혐...")
                # $ grouptalk.add("오덕현|그런건 오마에만 알고 있으라고!")
                # $ grouptalk.add("김진일|요즘 오덕체 떡상중이네")
                # $ grouptalk.add("연속|인터넷에서 개많이 쓰던데 ㅋㅋㅋㅋ")
                # $ grouptalk.add("오덕현|..그..치만 진일짱....")
                # $ grouptalk.add("연속|이렇게라도 하지 않으면")
                # $ grouptalk.add("연속|진일짱이 나를 봐주질 않는걸...")
                # $ grouptalk.add("해장중|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("유현재|개웃ㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("노미래|ㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋㅋ")
                # $ grouptalk.add("주인공|우리 내일 종판건 기억하지???")
                # $ grouptalk.add("주인공|가서 술마시자 ㅋㅋㅋㅋ")
                # $ grouptalk.add("동삼용|나 중국 갈 수도 ㅠㅠ")
                # $ grouptalk.add("김진일|가면 뻔대 또 의리주하냐 ㅋㅋㅋ")

            elif day == 6 :
                $ grouptalk.add("날짜|6월 21일 금요일")
                $ grouptalk.add("주인공|얘들아 이따 보자 ㅋㅋㅋ")
                $ grouptalk.add("주인공|많이 올거지???")
